### ISSUE TITLE
Preview rejected comment email 

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1017]
As a MET user, I want to be able to preview the email that will be sent when a comment is rejected. 

User is on the review comment page, clicks the "preview email" button.

Modal with the preview of the email _text_ opens, with the added Review Note and "other" if selected. 

Email template:

Title: Your comment on (Engagement name) needs to be edited

Thank you for taking the time to fill in our survey about (project name).

We reviewed your comments and can't publish them on our public site for the following reason(s):

_- One or many of your comments contain personal information such as name, address, or other information that could identify you.

One or many of your comments contain swear words or profanities.

One or many of your comments can't be published because of (other).

(Review Note text inserted here)

You can access your comment(s) to edit the text and resubmit here: "link will be added when email is sent"

Thank you,

The EAO Team

**Comment by carlygreenehill** [comment]
???

Button instead > "Send preview email to me" > Staff can put in their own email, and get sent a copy to check first

**Comment by carlygreenehill** [comment]
Would it be helpful if we had a list of things to change/update re: email templates?

**Comment by tiagograf-AOT** [comment]
https://docs.notifications.service.gov.uk/python.html#generate-a-preview-template

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1017?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @VineetBala-AOT @jadmsaadaot @tiagograf-AOT
