### ISSUE TITLE
New user MET registration

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1018]
As a new user of MET, I want to register with my IDIR and get a clear message of what I should expect.

##Scenario 1##

User logs in to MET for the first time, using their IDIR.

After login, sees the following message on the screen:

"Your login was successful and an email has been sent to ... to request access. Once your request is processed, you'll get a notification email to confirm you can now access MET with your credentials.

Thank you."

(email request sent to ...) eao.digital@gov.bc.ca

Request will be processed by Degital Services (AKA Geoff/Carly), they'll authorize the IDIR in Keycloak and email the user directly. 

Once added, user can be found on the MEt user management page.

Acceptance Criteria

New user should not be able to view or do anything with MET until permission set
Email sent once

**Comment by carlygreenehill** [comment]
Future needs for testing:

IDIR users testing Team Members, Admins, etc.
Create IDIR accounts 'dummy IDIR account' or go into Keycloak to do that?

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1018?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
