### ISSUE TITLE
Executive Dashboard

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1019]
MA UX testing:

There is a task to tweak the design a bit. It's in the backlog but I think it would be easier to do a change now than coming back to it later. 

Can you change the blue border for each section with the following:

Borders: To softer the look and make the element stand out, let's change all the borders in MET to:
border: 1px solid #cdcdcd
box-shadow: rgb(0 0 0 / 6%) 0px 2px 2px -1px, rgb(0 0 0 / 6%) 0px 1px 1px 0px, rgb(0 0 0 / 6%) 0px 1px 3px 0px;

You can close the task when done. 
------------------------------------------------
As an executive at EAO, I want to see a small dashboard of all the current and recently closed engagements on one page.

https://xd.adobe.com/view/30a6eeba-3e1d-47f3-b396-645d2667d8dd-65f5/

4 collapsible sections, each one with the details of the projects in that status:
Upcoming (no dashboard) - Default open
Open Engagements - Default open
Recently Closed Engagements (last 30 days) - Default open
Closed Engagements (over 30 days ago) - Default closed

All the engagements sections are closed by default and show:

Name of the engagement (h4)
Phase de engagement (p)
Dates of engagement (p)
(Flag icon for flagged engagement TBD)

When you click on the engagement section, it opens and shows a dashboard with the engagement stats and a button to access the full dashboard.

Engagement page visits
Survey completed
***V1 = show full report / report as is

(Sections to display tbd)
Button: View Full Report 

Desktop/laptop view: https://xd.adobe.com/view/30a6eeba-3e1d-47f3-b396-645d2667d8dd-65f5/specs/

Mobile version: https://xd.adobe.com/view/30a6eeba-3e1d-47f3-b396-645d2667d8dd-65f5/screen/68c9cd64-c426-44af-a935-ff24fec55e3b/specs/

SPECIAL NOTES

- No pagination for now
- React for stuff, redash for the other stuff
- Build the page Skeleton in React
- Embed the redash dashboard as IFRAME with in the page

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1019?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
Should we make a home page that isn't the engagement page?

**Comment by carlygreenehill** [comment]
Can we add same dashboard we already have in readash?

**Comment by saravanpa-aot** [comment]
1) Build the page Skeleton in React
2) Embed the redash dashboard as IFRAME with in the page

**Comment by VineetBala-AOT** [comment]
@tiagograf-AOT : Start and End date not appearing correctly.
