### ISSUE TITLE
IDIR users must be saved DB

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#102]
After a admin user successfully login, it's information (name, id) must be saved in the met database so that it can be used for display.

- [ ] end point to save admin user data
- [ ] data base
- [ ] edit front end

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/102?planning-poker) with ZenHub @djnunez-aot @jadmsaadaot @tiagograf-AOT
