### ISSUE TITLE
Change the way comments/dashboard is accessed by a public users

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1022]
1) Comment page should be accessible to a public user while engagement is open
2) Dashboard should be accessible only after an engagement is closed.

**Comment by VineetBala-AOT** [comment]
Additional AC:
3) For internal user both dashboard and comment page should be accessible any time.
4) Link in the email should lead to comment page.

**Comment by tiagograf-AOT** [comment]
If i try to access the comments page as a public user I get a blank list of records (if internal user it displays the comments)
![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/c548f1db-b0fa-48b0-b50a-fdf40678cb21)
![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/df408d30-5968-4ba9-8730-56a488a21f05)

I noticed some engagement won't show the "View Report" option in the listing:
![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/22c42fd7-5ec5-4d5d-aafa-4cc5a821e97f)
