### ISSUE TITLE
Update rejected email content to add Review Note

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1029]
Email template:

Title: Your comment on (Engagement name) needs to be edited

Thank you for taking the time to fill in our survey about (project name).

We reviewed your comments and can't publish them on our public site for the following reason(s):

_- One or many of your comments contain personal information such as name, address, or other information that could identify you.

One or many of your comments contain swear words or profanities.

One or many of your comments can't be published because of (other).

(Review Note text inserted here)

**The engagement period is open until _________ (end of survey date range)**

Thank you,

The EAO Team

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1029?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Tested with Vineet, @marieanik please take look.
