### ISSUE TITLE
Day calculator

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1031]
As an admin, I want to be able to calculate the day of an engagement automatically with a day calculator.

Matches wireframes:
https://xd.adobe.com/view/7d5f6547-2523-484d-8101-a7587f9076c8-280c/screen/c782aea0-9827-4d52-b157-d26401f53f21/
https://xd.adobe.com/view/7d5f6547-2523-484d-8101-a7587f9076c8-280c/screen/d387f7e6-c2db-4713-8e5a-31f1411e1cce/

The calculator will be the same as in EPIC (logged in as Admin, link in the top right corner)

There are three calculation types (drop-down):
-Day Zero
-Calendar
-Suspension

![Screen Shot 2022-12-19 at 6.59.26 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/7cea1a61-0dfa-4cd2-9176-78f29f69e082)

**Day Zero** has the option to show text that explains it (smaller text: 13px):
![Screen Shot 2022-12-19 at 7.03.03 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/e0c34a52-59f5-46f7-9323-cf68a166a42d)

"Description
Start date is excluded from calculation. Hide Day Zero rules.

Holidays
If a deadline falls on a holiday the deadline is extended to the next day that is not a holiday. For example, if the deadline for a comment period is December 26, boxing day, the deadline is extended to December 27.
Weekends or Other Office Closures
If a deadline falls on a day when the office is not open (Saturday, Sunday) the deadline is extended to the next day that the office is open. For example, if the deadline for a comment period falls on a Saturday then the deadline is extended to Monday.
Calculation of Days
When calculating periods (for example 30 day comment period) the first day must be excluded and the last day included. For example, a 30 day comment period starts March 1, 2017, the comment period does not end until March 31, 2017.
Legislated time periods must be calculated with day -0- eg, Evaluation 30 days, Application Review 180 days, Ministers Decision 45 days, and Public Comment Periods.
Time of Day
There is no specific mention of time of day in the Interpretation Act so the day would end at midnight. If a comment is received before midnight on the last day of the comment period it would be included in the comment period. If an email was received at 11:59PM it would be received in the comment period or if a written comment was received at an open house before midnight then the comment would also be included in the comment period. Comments sent by mail or courier must be post marked by the last day of the comment period in order to be included in the comment period.
Suspension
Suspending a project during the Application Review period, when the suspension resumes it starts back on the day it was suspended on. If a project is suspended on day 50 of the 180, in accordance with the spirit of the Act, day 49 was the last full day of the Application Review Period, when the project resumes, it would resume on day 50 to allow 180 full days of review.
Interpretation Act
25  (1) This section applies to an enactment and to a deed, conveyance or other legal instrument unless specifically provided otherwise in the deed, conveyance or other legal instrument.

(2) If the time for doing an act falls or expires on a holiday, the time is extended to the next day that is not a holiday.

(3) If the time for doing an act in a business office falls or expires on a day when the office is not open during regular business hours, the time is extended to the next day that the office is open.

(4) In the calculation of time expressed as clear days, weeks, months or years, or as "at least" or "not less than" a number of days, weeks, months or years, the first and last days must be excluded.

(5) In the calculation of time not referred to in subsection (4), the first day must be excluded and the last day included.

(6) If, under this section, the calculation of time ends on a day in a month that has no date corresponding to the first day of the period of time, the time ends on the last day of that month.

(7) A specified time of day is a reference to Pacific Standard time, or 8 hours behind Greenwich mean time, unless Daylight Saving time is being used or observed on that day.

(8) A person reaches a particular age expressed in years at the start of the relevant anniversary of his or her date of birth."

**Calendar**
![Screen Shot 2022-12-19 at 7.02.32 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/83dd7514-f422-4e12-9a5f-18ea930e9cc6)

**Suspension**
![Screen Shot 2022-12-19 at 7.02.12 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/531db94c-1fc6-4635-88f2-2cdb4bac784b)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1031?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by saravanpa-aot** [comment]
https://github.com/bcgov/eagle-admin/blob/develop/src/app/day-calculator-modal/day-calculator-modal.component.html

**Comment by tiagograf-AOT** [comment]
Layout needs to match the wireframes/MET standards
