### ISSUE TITLE
Purge submissions containing PI after a period of inactivity

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1034]
As a MET admin user ,
I want the submission containing PI to be purged 
If the submission is not updated by user after submission period

So that database doesnt have any PI data

**Comment by tiagograf-AOT** [comment]
Questions raised:

Should we keep the other user answers? like (radio boxes, etc) and just erase the free-text comment?
Should we keep the data for a period of time or as soon as is rejected we should erase it?

**Comment by tiagograf-AOT** [comment]
this has been implemented in another story.
