### ISSUE TITLE
Create a mock redux store for front-end unit tests

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1080]

**Comment by jadmsaadaot** [comment]
FOI project has a pattern for this

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1080?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Closing this since we don't use the store enough for having units
