### ISSUE TITLE
As a public user, I want to see the results for a survey. (Also, Mobile Friendly)

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1098]
Show the radio and checkbox type questions as a clickable question list with related data on the right as in below screen shot.
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/e4ace557-3df5-4824-9bef-cfb7ce5a3cb1)

As a public user I would like to see the survey results using the bang the table plugin. Questions on the left and Visual references on the right.

![Screenshot 2023-04-24 at 10.15.10 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/e84fa405-bcbb-44d5-a002-c76e55898f4c)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1098?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
New API endpoint
Two ways of displaying the data.
Display should be responsive
