### ISSUE TITLE
SPIKE: form.oi tweaks research

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1101]
As discussed, research to determine the feasibility and time required for the following changes:

- Make the "drag and drop" blue box always visible, even after adding a question.
- Rename the "Basic" header on top of the questions/survey components (name tbd)
- Change the name of the "Data" tab (name tbd)
- Hide the "Values" and "Shortcuts" section in the table on Data tab and make "labels" mandatory (checkboxes, category checkboxes, and radio)
- Hide the "Search field(s)" search bar
- Turning on the multi-page option will delete all the pre-existing survey questions added (even after being saved). Can we do anything to prevent that?

**Comment by jadmsaadaot** [comment]
Make the "drag and drop" blue box always visible, even after adding a question. (Can't be done)

Rename the "Basic" header on top of the questions/survey components (name tbd) (Removed the name)

Change the name of the "Data" tab (name tbd) (Renamed to Values)

Hide the "Values" and "Shortcuts" section in the table on Data tab and make "labels" mandatory (checkboxes, category checkboxes, and radio) (Can't be done)

Hide the "Search field(s)" search bar (hid)

Turning on the multi-page option will delete all the pre-existing survey questions added (even after being saved). Can we do anything to prevent that? (Can't be done)

**Comment by jadmsaadaot** [comment]
Make Label field required for checkboxes and radios
