### ISSUE TITLE
Assosiate staff user to a tenant/ministry

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1113]
When a staff user logs in , we should have a process to associate the user to a ministry.

Questions:

With a new user registration, when granting access can a Admin assign the membership to any tentant or only the current tenant?

When new user logs in (user registration), do we pass along the tenant which the user is trying to sign in to?

**Comment by tiagograf-AOT** [comment]
Site URL will specify the TenantId
Access check for the logged in user should be based on the membership table with tenant id
User Registration now must pass the tenant id

**Comment by saravanpa-aot** [comment]
a user being present in multiple ministries(tenant) is not handled ..
its unlikely except for super users (Steve) who might create a tenant.. still they will belong only to one ministry

**Comment by VineetBala-AOT** [comment]
verified, when a user registers into one tenant the tenant id is passed and stored in the table.
