### ISSUE TITLE
Document widget creates empty folders

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/met-public#1116]
When a user does not enter a name for a document it creates an empty folder.

![image](https://user-images.githubusercontent.com/103138766/212982912-43672b15-18e6-4252-b520-defd24805bc0.png)

**Comment by VineetBala-AOT** [comment]
@djnunez-aot , its still happens when creating the first time.

**Comment by VineetBala-AOT** [comment]
Validated and working fine in development.
