### ISSUE TITLE
Add basemodel to all models

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1124]
Extend from basemodels

remove common fields

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1124?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Validated in development, its looking good.
