### ISSUE TITLE
Align top of widgets with top of content box, make sure spacing is consistent

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1128]
The top widget is sometimes higher than the content by about 10px.
I also noticed the spacing is not always the same in between the widgets.
Bio also does not use empty spaces on the right

![Screenshot 2023-01-18 at 3.40.51 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/066e69a5-099c-48cc-b1a7-2bdcf567c553)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1128?planning-poker) with Zenhub @djnunez-aot @Ian-UX-AOT @jadmsaadaot @saravanpa-aot @VineetBala-AOT
