### ISSUE TITLE
show which environment the email belongs to 

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1130]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/39633456/213523726-94b568ae-5221-4521-bcee-32e10b231fea.png">

It might be easier for staff to know which environment the mail is from ;ie DEV/TEST/DEMO/PROD etc..

Solutions
Can put the url so that its visible
color code the mail (leave nothing for prod)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1130?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Verified all emails having text at bottom showing which environment the email is from.
