### ISSUE TITLE
As a internal MET system user, I want to be able to see more clearly each row in the tables

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1138]
Add a #f2f2f2 line between each row in each row in all tables in MET

![Screenshot 2023-01-24 at 9.14.41 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/9552a931-8d5c-45cc-bfdb-05c498919388)

**Comment by jadmsaadaot** [comment]
just don't pass noRowBorder={true} and the rows should appear back
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/8eb559e5-d7d7-4047-b4fa-6c06ea9a7b04)

**Comment by jadmsaadaot** [comment]
just don't pass noRowBorder={true} and the rows should appear back
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/8eb559e5-d7d7-4047-b4fa-6c06ea9a7b04)
