### ISSUE TITLE
Engagement User Roles Rules

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1139]
Link to Spreadsheet in Teams: `https://bcgov.sharepoint.com/:x:/t/04610/EbN6-RHdb5pIqqJrtaNdqocB-dhFxd39Q8OxvrV8_wKraw?e=Oqk2Cl`

Here are the permissions for the ENGAGEMENT pages, organized by each Role

![Screenshot 2023-02-14 at 12.19.24 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/debf4a50-65c8-4c29-a034-f1ba6ce8b015)

The engagement name will always be the link to "preview" the engagement. 
The entire row will be visible or not depending on role/status (i.e. Viewer won't see any draft engagements)
Create Engagement button will be greyed out for TM/Viewers

**Comment by carlygreenehill** [comment]
MET team talking about this card on Thurs Feb 9 :)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1139?planning-poker) with Zenhub @jadmsaadaot @VineetBala-AOT @saravanpa-aot @djnunez-aot

**Comment by carlygreenehill** [comment]
ADD THE ROLES

**Comment by jadmsaadaot** [comment]
Related spike ticket https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1089

**Comment by VineetBala-AOT** [comment]
Verified:
Create Engagement button is greyed out for TM/Viewers.
Draft engagements not visible to TM/Viewers.

- disable non-admin unassigned user to go to edit engagement page will be handled as part of ticket : https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1281
