### ISSUE TITLE
User Management - Revoke Reviewer/TM from engagement

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1140]
Link to Spreadsheet in Teams: `https://bcgov.sharepoint.com/:x:/t/04610/EbN6-RHdb5pIqqJrtaNdqocB-dhFxd39Q8OxvrV8_wKraw?e=Oqk2Cl`

As a MET system user, I want to revoke a Reviewer or TM from an engagement they are assigned to while keeping their information (association to engagement) in the system so that I have a history of who was assigned to an engagement. 

Acceptance Criteria:

Based on roles, MET users can revoke a Reviewer/TM from an engagement.
User Detail and engagement (UM tab) shows the user's status as dates ("Assigned on" & "Revoked on" columns)
Soft delete >> Change the record from active to inactive

![Screenshot 2023-06-20 at 12.37.50 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/fb693be8-affa-4edb-8f65-11796e3bdffc)

Implement versioning and history

**Comment by marieanik** [comment]
Taya will create wireframes for this task.

**Comment by TayaLee8** [comment]
From the **User Management tab** in an engagement:

![Screenshot 2023-06-27 160645.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/a00889d5-dfa8-4ddc-8bc0-66d9e3045d8d)

Each **Action** drop-down will have options: **Revoke** and **Add**. One drop-down option will always be disabled according to the users current status. 
Ex) Jack Black cannot be revoked from the engagement as they are already revoked. 

![Screenshot 2023-06-27 160739.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/ce64154f-e124-4a23-8604-42b39328ee4f)
![Screenshot 2023-06-27 161406.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/594c13c9-8dc5-423d-8cc5-ca233dafe5e2)

A pop-up will appear after a user is Revoked/Added.

History of who was assigned to an engagement will be viewable through the user details page - see example in  [https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1273](url).

**Comment by carlygreenehill** [comment]
All this card needs is some "filler text" explaining to a back end user what happens when they revoke a Reviewer or TM.

**Comment by VineetBala-AOT** [comment]
Verified as a TM. 

Reviewer is still able to see the engagement in listing. This will be handled as part of ticket 2006.
