### ISSUE TITLE
Observations on Add a Team Member to this Engagement

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1151]
3) Team member not appearing in the drop down list. In the user management tab we can see one user shows as a member but same not displayed in the drop down.
               Search as we type -  Improvement
               Validate on post - Discuss with MA

Validation message:

This user is already an Administrator. 
This Team Member is already assigned to this engagement.

Adding bugs related to 1074 here:
1) Same success message while adding user as an admin or team member. Needs to be updated so that its same as in the ticket.
2) On the user management page even if individual is a team member it shows as viewer, but if you add as admin he shows up as admin.

**Comment by jadmsaadaot** [comment]
I have discussed with @marieanik whether it is okay to have the validation of whether the user is already an admin or already a team member of the engagement after the submit button is pressed. In that case the flow is submit is pressed, button is loading, result is returned with error, red error message appears under error field just like what we do with other forms.

**Comment by VineetBala-AOT** [comment]
verified all ACs met. 

The issue "On the user management page even if individual is a team member it shows as viewer, but if you add as admin he shows up as admin." will be fixed as part of 1205
