### ISSUE TITLE
Updates to the Engagement creation page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1152]
MA note: Let's make the sections "tighter" by moving the label closer to the description text or input field. Also, small tweak to make it less "busy": make the description 13px ( and line height around 1.1em)![Screenshot 2023-02-14 at 2.46.26 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/8bf38695-50f2-4db7-b0af-81a7f336e2ba)

Reorganization of the Engagement page.

https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/c782aea0-9827-4d52-b157-d26401f53f21/

Change the order of the fields and add a description below the label (16px regular #707070):

Engagement Name
Desc: This will be the main header on your engagement page.

Engagement Date
Desc.: This is the date the public engagement will be open to the public. 

Upload Header Image *add label currently missing

Engagement Description
Desc.: This is a short description that will show in the header section of the engagement page. The recommended length is 250-500 characters.

Engagement - Page Content
Desc.: This is a the main content of the engagement page.  

Survey (as is)

Also, let's remove the outer "Block" for the content. It was designed to have image and image placement but as is, we don't need the double container. It should be like the description.

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1152?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
