### ISSUE TITLE
Ui Modal Fixes

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1157]
Text on the modal is "Add a Team member to this engagement" but in the design its "Add a Team Member to this Engagement" note the caps in M and E

Another one is "Select the user you want to add" but in design it is "Select the Team Member you want to add"

Date created shows complete timestamp, only date is required and it needs to be converted to PST before display.
                    fix now - Jad

**Comment by jadmsaadaot** [comment]
I remember it was agreed that the title of the success notification would be removed. I suggested in that case that the notification becomes the snackbar the appears from the bottom left. So converted it to snackbar success message
