### ISSUE TITLE
Add Events (open house/Virtual session) widget  - add widget and main widget page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1168]
As a MET system user, I want to be able to select the Events widget to add to my engagement.

Matches wireframes:
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/6d417aa6-949b-44f1-9c53-0b1063a45215/
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/cf16f054-656b-459e-be86-2d03363a5601/

Events widget cards shows on engagement page.
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/bb9b396f-f693-4922-aa7b-1296699b0d45/

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1168?planning-poker) with Zenhub @djnunez-aot @Ian-UX-AOT @jadmsaadaot @saravanpa-aot @VineetBala-AOT
