### ISSUE TITLE
Purge EventLogs to reduce database size

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1171]
Reduce the database volume size by having a job schedule to purge some of the event logs generated by redash and dagit.

Dev environment db is already at 2gb with little to no actual data. It is increasing on average 1 gb every 2 months.

**Comment by saravanpa-aot** [comment]
https://github.com/bcgov/met-public/blob/main/docs/cleanup_space.md
Got a few basic steps in there for a handy reference
