### ISSUE TITLE
Add open house to the Event widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1181]
As a MET system admin, I want to add one or many open houses to the event widget.

##Scenario 1##

User is on the Event creation tab and clicks "Add Open House"

Header: Open House (not editable)
Input fields (all mandatory):
Location Name
Location Address
Date
Time - From, Time- to
Description (optional)

Buttons: "Save & Closed" "Cancel"

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/25e020cd-1d2f-4fa9-836e-22cf209837e8/

##Scenario 2##

User clicked the "Save & Close" after entering all the information required. Goes back to the main Event widget tab. Card with the Open House info is now visible.

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/7622f03e-f681-4fc8-a05b-263dcefb1a64/

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1181?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
