### ISSUE TITLE
Add Virtual Information Session to the Event widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1182]
As a MET system admin, I want to add one or many open houses to the event widget.

##Scenario 1##

User is on the Event creation tab and clicks "Add Virtual Session"

Header: Virtual Information Session (not editable)
Input fields (all mandatory):
Date
Time - From, Time- to
Virtual Session Link
Virtual Session Link - Text Displayed *Field pre-populated with "Click here to register"
Desctiption (optional)

Buttons: "Save & Closed" "Cancel"

Matches wireframes: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/d6e412c8-1e3c-424f-8dd2-f1257cafe2d2/

##Scenario 2##

User clicked the "Save & Close" after entering all the information required. Goes back to the main Event widget tab. Card with the Virtual Session info is now visible.

Matches wireframe:https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/e8d73e28-1d58-41c1-8fed-ef9194450c73/

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1182?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Verified in dev, all acceptance criteria met.
