### ISSUE TITLE
Event widget is visible on the engagement preview/published engagement

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1184]
MA note: Can we reduce the padding-top from 8px to 4 px for the details of the event and make the label bold, please?
Reduce the padding by about 10px between the events.

Also, I noticed the same alignment issue with that widget:
![Screenshot 2023-02-27 at 12.01.17 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/94fed4ef-c7f6-401a-ad32-22d761977a65)

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/cd4852cd-5b93-4d9e-9428-2e2f6e2e4dea/

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1184?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Verified, event widget is visible on preview/published engagement
