### ISSUE TITLE
Define configurable items across Ministries

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1189]
What all items , we can configure for a ministry

The banner: Will be MET but they will upload their logo
The color themes: same for internal but the ability to define colour theme (per engagement) will be required by GDX (TBC)
What all texts?

**Comment by carlygreenehill** [comment]
EAO Phases widget?
Which widgets allowed?

**Comment by marieanik** [comment]
Covered in other tasks. Closing this one.
