### ISSUE TITLE
Bug: Email delayed Subscribe Widget and Edit Comments

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1194]
The emails for Subscribe Widget and Edit Comments came in half hour ish later after I clicked buttons

<img width="897" alt="image" src="https://user-images.githubusercontent.com/39633456/216478809-b12d2d9a-97d8-4f7d-943c-719f5a05cc78.png">

Compare the timestamp of the records in DB to see if the delay is actually in our system or in gc notify

**Comment by carlygreenehill** [comment]
@TayaLee8 can you test this to see if it's still happening

**Comment by TayaLee8** [comment]
I did not experience an email delay when subscribing, or when my comment was rejected and needed to be revised @carlygreenehill @saravanpa-aot
