### ISSUE TITLE
Design tweaks on comment page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1224]
**MA NOTE**Eidts needed: more detail in Comments below.

Move the Read All Comments and Return to comment list buttons to top right corner (above the table)![Screenshot 2023-02-10 at 12.19.23 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/9a0762a8-92dd-4b8e-9049-6cb2e358461b) 

Matches wireframe: https://xd.adobe.com/view/314be723-38ea-4f16-acb4-69db36ac71f9-6418/screen/90332d54-a3fd-41e6-a174-36a4d976c126/

**Comment review page**

Move the rows of info on top closer to each other, and every section just a bit closer

![Screenshot 2023-02-09 at 10.16.49 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/1a815f11-f185-4d89-a3ed-1d72e1418c1f)

**Change the order of the rows of info so the first column is Comment ID, Comment Date and the second column is Status, Reviewed By, Date Reviewed.**

Add the "Contains threat/menace" checkbox in the list of "Reasons for Rejection"

Change the style of the lines: 

(this will be inserted in the email sent to the respondent in the following sentence: One of your comments can't be published because of "other")

And 

(this note will be inserted in the email sent to the respondent to help them understand what needs to be edited for their comment(s) to be approved.)

To match the description on the Engagement Details page (remove parentheses, on the line below the label, in 13px #707070)

Make the headers "Comments Approval" and "Reason for Rejection" #494949

**Read All Comments page**

Comment date and Reviewed By (label and text) need to be 16px. Separate submission with a line (Add a #f2f2f2 line between each submission - not individual comment)  if not already done in https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1138

Also, can we make those columns the same width and aligned from top to bottom to make it easier to read? Comment date is in line with the first line of question/comment. Questions are showing above the comment.![Screenshot 2023-02-10 at 2.42.31 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/fff5fd31-0529-48c8-9625-fb0abcaacde0)

**Comment by marieanik** [comment]
Edits needed:

Review comment page: Change the order of the rows of info so the first column is Comment ID, Comment Date and the second column is Status, Reviewed By, Date Reviewed.

Comments on the image below.
New sentence for threat: 
If there is a threat/menace in the comments, select this checkbox and contact <TBD>. No email will be sent.
![Screenshot-2023-04-27-at-10.16.19-AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/c05b72de-c87f-4e05-a02a-2e7103069c98)

**Comment by tiagograf-AOT** [comment]
@djnunez-aot 
"Return to comment list" still in the wrong location.

columns also not taking the spaces properly?!:
![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/2f2edd02-7cd3-41dc-9659-385605bf5a6c)
