### ISSUE TITLE
Save a survey as a template

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1225]
As a Superuser, I want to be able to save my survey as a template so these templates can be cloned but not edited directly.

Superuser is on the "form.io Create Survey" page, and toggle on the "Save as a Template" toggle and save the Survey. Survey will be saved as a template and will only be available to be cloned (not attached directly to en engagement). Cloned Template will become editable by TM assigned to the Engagement they are assigned to.

Tooltip: When you toggle ON this option and save your Survey, your Survey will become a Template. As long as this option is on, the Template can be cloned (and then edited) but can't be attached directly to an Engagement. 

matches wireframe: https://xd.adobe.com/view/314be723-38ea-4f16-acb4-69db36ac71f9-6418/screen/cefb6c98-337c-426b-96c6-e45dc617ee62/

Spreadsheet with all the options: `https://bcgov.sharepoint.com/:x:/r/teams/04610/Shared%20Documents/General/User%20Management.xlsx?d=w11f97ab36fdd489aaaa26bb5a35daa87&csf=1&web=1&e=SPkc20`

**Comment by carlygreenehill** [comment]
1. Support saving a survey as draft
2. Don't show draft surveys for cloning yet
3. Don't show draft survey to non-team members

**Comment by jadmsaadaot** [comment]
According @marieanik @tiagograf-AOT to our discussion:

Hidden and template are flags,
The statuses are Ready, hidden, template
