### ISSUE TITLE
Search filter not working on read all comments page

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1229]

**Comment by carlygreenehill** [comment]
So far, I can search for comments in TEST in the Read All Comments and Comments List, but I can only search using comment ID. I do not get any results when I try to search by text.

**Comment by VineetBala-AOT** [comment]
@carlygreenehill , we can search it with the id but in that case I think we need to update the text to say search comments by id as in other pages we search by the text and not by the id. I created this bug with the understanding that we can search a comment using any keyword text within the comment.
