### ISSUE TITLE
Engagement Tile - Export as Webcomponent

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1242]
Follow up on https://github.com/bcgov/met-public/issues/1237
1) Bundle 
2) Npm linking 
3) Test in EPIC

**Comment by marieanik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1242?planning-poker) with Zenhub @dinesh-aot @jadmsaadaot @saravanpa-aot @djnunez-aot @VineetBala-AOT
