### ISSUE TITLE
Edit & Delete within Event Widget

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1258]
As a Team Member/Superuser, I want to be able to...

1) Edit option for both In-Person Event and Virtual Session
2) Enable delete for both In-Person Event and Virtual Session

so that the Widget information displays accurately to the public user. 

**Acceptance Criteria**

UX links: 
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/7622f03e-f681-4fc8-a05b-263dcefb1a64/
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/25e020cd-1d2f-4fa9-836e-22cf209837e8/

- Delete event items completely
- Delete needs a confirmation
- User can edit all Event Info

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1258?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
