### ISSUE TITLE
Formio Form Builder Customization Research

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#126]

**Comment by jadmsaadaot** [comment]
The progress in this task were added to formio-customization branch in our repo:

- We have explored the manipulations we can do on the Formio options to remove/create component sections and new component.
- We explored how we can edit the edit form modal that appears when a component is dragged and drop to remove any redundant fields.
- We have explored how to create a new code module that hosts custom components and how to integrate it with our current module
- We found that cleanest way to customize the edit form modal is to create a simplified version of any component we wish to use.
- We have reviewed what the CHEFS team (https://bcgov.github.io/common-service-showcase/services/chefs.html) and found that their example is a good approach.
 

After discussing our findings, we find that creating a new repository that hosts the code module for custom formio components which can be either published to NPM or kept on github would be a clean approach and would allow for easy integration in the MET project.
