### ISSUE TITLE
Sort Events/Sessions with Event Widget

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#1263]
**As a** Team Member/Superuser

**I want** to sort Events or Sessions within the Event Widgets

**so that** I can communicate the priority of events nicely to public users. 

### Scenario 1: 

User should be able to re-order

GIVEN ... a list of existing Events/Sessions that have just been entered
WHEN ... a user sorts the "cards" to their liking
THEN ... the Events/Sessions show up correctly to backend users and public users

### Validation Rules? 

If cards get re ordered, needs to save right away. User hits "close" when they are finished sorting.

### Screenshot 

https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/cd4852cd-5b93-4d9e-9428-2e2f6e2e4dea/

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1263?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by saravanpa-aot** [comment]
Tested;looks good
