### ISSUE TITLE
Deactivate User from User Details page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1273]
As an Instance Admin, I want to deactivate a user from the User details page.

To Deactivate a User means to revoke access to MET, revoke all their privileges as a Reviewer/Team Member on Engagements, but keep the history of what they worked on. It also means that they are no longer a Superuser if they had this role assigned to them.  

The "Deactivate User" button is only enabled if the user is Instance Admin.
"Add to Engagement" button is disabled if user is a viewer
User status will be updated on UM listing page.

Superuser/Instance Admin sees the confirmation modal to confirm user will be deactivated
Then sees the green notification message (green popup message): 
"You have successfully deactivated (user name)."

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1273?planning-poker) with Zenhub @jadmsaadaot @tiagograf-AOT @VineetBala-AOT

**Comment by marieanik** [comment]
Taya will create wireframes for this task.

**Comment by TayaLee8** [comment]
From the **User Management** tab on side navigation:

![Screenshot 2023-06-27 162303.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/937e34d1-b61a-4906-87e2-33545ebc107f)

When a username is clicked, you navigate to the **User Details** page. This is where a the historical list of who was assigned to engagements will live.   
![Screenshot 2023-06-27 162508.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/40a02ce7-e4e2-4ad5-8e37-cda357991c50)

When the **Deactivate** OR **Reactivate** (depends on user status) button is pressed, a pop-up will appear:
![Screenshot 2023-06-27 162933.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/6fa044ed-1c3b-438a-98e9-f4df903e397a)
![Screenshot 2023-06-27 163007.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/f4ee2413-7d06-4777-bb28-ebda18ddf556)

**Comment by carlygreenehill** [comment]
Filler text to explain on the modals what happens when you do x, y, z

**Comment by TayaLee8** [comment]
When a user name is clicked, the User Details (second screen) displays.
When Deactivate User is clicked, the "Deactivate <user name>" pop-up modal appears.
**if possible with existing IDIR configuration** When Reactivate User is clicked, the "Reactivate <user name>" pop-up modal appears.

Deactivating a user means that they will be deactivated completely from MET including all assigned engagements. Once a user is deactivated, the date they were deactivated will appear on the User Management page (first screen).
