### ISSUE TITLE
Mobile - Pop up blocks user info entry

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1275]
User can't scroll to text box for email entry in mobile mode. Background keeps scrolling but pop up is locked. 

"There was one bud I found on using an iPhone 7 and that was the pop up when you go to accept the user agreement and input your email address." -Sid

![Iphone map copy 9@0.5x.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/c4510e81-5dd8-421c-9894-3b8a7923ec5a)

**Comment by VineetBala-AOT** [comment]
Verified, looking good on mobile.

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/5158b896-9fa9-4f99-a910-a2114620b9eb)
