### ISSUE TITLE
Button text resize or reword

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1286]
MA note: should be solved by https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1285

Button text overlaps container: Either decrease the text size or shorten the phrase- maybe just 'sign up'
![Screenshot 2023-02-27 at 2.10.10 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/bff5e35e-5cca-432f-9bd4-4d8fbc6a7d4d)

**Comment by marieanik** [comment]
Fixed with 1285
