### ISSUE TITLE
Add a map Widget

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1289]
**As a** engagement team member 

**I want** to add a map widget to my engagement

**so that** I can show a visual map to the public

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/6d417aa6-949b-44f1-9c53-0b1063a45215/specs/

**ACCEPTANCE CRITERIA**

- No map-y things, eg. no need to view from preview page
- Widget is in drawer, can be added to engagement form page in the widget block

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1289?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT @Ian-UX-AOT @marieanik

**Comment by carlygreenehill** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1289?planning-poker) with Zenhub @Connor1892

**Comment by VineetBala-AOT** [comment]
Verified, user is able to add the map widget to engagement form page in the widget block
