### ISSUE TITLE
As a member of the public, on the engagement page, I can see a map with a pin showing me a lat/long for where the proposed project is

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1291]
As a public user 
when i open an engagement with mapping widget
I should be able to see a mapping widget with specified lat long being show

ASSUMPTION

- Map library chosen in #1290
- But could be different between the cards... preview has to be zoom level (pin is centered within screen zoomed in to XX) Can be bigger because on full page for public user
- Mobile view??

ACCEPTANCE CRITERIA

- Map Widget added to engagement with lat/long > shows correctly to public user
- Public user doesn't get stuck in a massive map view

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/4deac341-a387-4a45-8ee1-47f963e3f05a/specs/

Neat example from BTT: https://demonstration.engagementhq.com/places/maps/washington-dc-police-districts1

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1291?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1291?planning-poker) with Zenhub @Connor1892

**Comment by jadmsaadaot** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1291?planning-poker) with Zenhub @marieanik
