### ISSUE TITLE
An Admin can Log In with IDIR

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#13]
Description:

As a Admin user I would like to use my goverment account (IDIR) to login into the MET application so that I can manage engagements within the app.

Acceptance Criteria

Users can login using IDIR

Associated tasks - 
- [ ] #78
- [ ] #63

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/13?planning-poker) with ZenHub @saravanpa-aot @nikhila-aot

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/13?planning-poker) with ZenHub @tiagograf-AOT @djnunez-aot @jadmsaadaot

**Comment by nikhila-aot** [comment]
Do we have the IDIR configurations required for KeyCloak setup ?
