### ISSUE TITLE
Remove DefaultMethodResult from backend

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/met-public#1302]

**Comment by saravanpa-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1302?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT @Ian-UX-AOT @marieanik
