### ISSUE TITLE
Public view - Expanded map

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1310]
As a member of the public, on the engagement page, I can see an expanded view of the map so I can see the location with more context.

User clocks the "View expanded map" icon/link on the map widget. Sees a larger view of the map

Matches wireframe: https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/ba12c326-575a-4d76-b0f1-819803a3abb3/specs/

**Comment by saravanpa-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1310?planning-poker) with Zenhub @jadmsaadaot @djnunez-aot
