### ISSUE TITLE
form.io edit form pop-up becomes stuck if background page is changed

### ISSUE THREAD

**Issue by TayaLee8** [bcgov/met-public#1327]

**Comment by TayaLee8** [comment]
Talked to Jad about this and confirmed it was a bug and needed a ticket @jadmsaadaot

**Comment by TayaLee8** [comment]
**On MacBook**
1. User goes to add a form component to a survey
2. After dropping the form component, a pop-up appears
3. User accidently navigates back to the previous **background** screen (two finger swipe on MacBook)
4. The pop-up becomes stuck, the user cannot save, cancel, or remove their form component and is forced to close the tab 

https://user-images.githubusercontent.com/122818332/226674157-8844c7eb-300c-47a3-8984-554d9c3305f8.mov

**Comment by carlygreenehill** [comment]
@jadmsaadaot + @TayaLee8  + @marieanik  --- did we fix this bug or does it still need our attention? Please reply to this comment if it is still a thing. 

I'm ranking this a $$$ (big money, high priority) bug if it's still active because it might lead to Survey Creators losing all their work.

**Comment by marieanik** [comment]
gng
