### ISSUE TITLE
As a TM/super user, I want to customize the name of my widgets

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1329]
As a TM/super user, I want to customize the name of my widgets so I can use them in different ways.

For example, renaming the "Events" widget to "Open Houses" or the Who is Listening to "Meet the Team"

**Comment by carlygreenehill** [comment]
@jadmsaadaot  out of the top of your head, how much effort would this take

**Comment by VineetBala-AOT** [comment]
Verified.
