### ISSUE TITLE
Shapefile upload to the database

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1337]
As a Staff user I want to upload shapefile when the map widget so that we can show a area location location instead of a single point.

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1337?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Upload .zip file.
Unzip and convert from SHP to jojson.
Save converted version to database.

**Comment by tiagograf-AOT** [comment]
https://maplibre.org/maplibre-gl-js-docs/example/geojson-markers/
