### ISSUE TITLE
TM can only clone a template or attach a survey to an engagement

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1367]
On the engagement Details page, TM clicks the "add survey" button. Sees the options:

Clone an existing Survey/Template (sees all Approved templates & all Approved, linked, Scheduled, Published, Open, and Closed surveys)
Add an existing Survey to my engagement (See all Approved Surveys that are not a template)

"Create Survey" button on the survey listing page is disabled.

![Screenshot 2023-03-22 at 9.54.31 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/1b0bf7b5-5173-41cc-855b-f8d64038bd04)

**Comment by marieanik** [comment]
Duplicate of #1225

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1367?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Remove Create New Survey Option from "Create Survey from Engagement page"
Remove "Template" Surveys from list of "Attach an existing Survey"
Templates can be cloned only so that means only super users can edit template surveys
New isTemplate column
