### ISSUE TITLE
"Empty" comments shouldn't require review, and show up in the "read comment" (internal and external)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1370]
If no comments found in a submission it should be automatically approved.
Filter out submissions that have no comments in the listing pages (list and read all).

**Comment by saravanpa-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1370?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot

**Comment by saravanpa-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1370?planning-poker) with Zenhub @tiagograf-AOT @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
If no comments found in a submission it should be automatically approved.
Filter out submissions that have no comments in the listing pages (list and read all).
