### ISSUE TITLE
As an Admin, I want to select a widget  so I can add it to an Engagement.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#138]
As an Admin
I want to select a widget 
so I can add it to an engagement

### Scenario 1: 
Confirm user interface to the visual design
https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/d5ff35b0-90ea-49eb-a8f2-fe307a156b92/specs/ (Add Widget button)
and https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/cca8437e-bd10-4dc8-b325-d8e824b6ea33/specs/ (select widget: Who is Listening)

### Scenario 2:
- Admin clicks the "Add Widget" in the Widget section.
- Admin selects the "Who is Listening" card from the widget cards on the widget selection panel.

### Screenshot 
(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-24 at 4.39.50 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/b1abaa42-a855-4d2b-8aa3-99955bddbd17)![Screen Shot 2022-05-24 at 4.40.26 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/beec9021-ae6e-490a-b42f-e1cc2abb8f4c)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/138?planning-poker) with Zenhub @tiagograf-AOT @djnunez-aot @jadmsaadaot @VineetBala-AOT @saravanpa-aot

**Comment by carlygreenehill** [comment]
Jad kept working really hard on MORE than this card contained.
