### ISSUE TITLE
Preview/View show upload shapefile  

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1382]
UX Notes:

If a shapefile is uploaded, Lat/Long should be optional (we can leave it mandatory until we get to it)
I saw a bug was created for the map not showing so I'll ignore that for this task. 
Can you please add the description for the Lat, Long. and marker labels? (Same style as on the engagement details page. You can see them on wireframes.)

As a MET system user, I want to be able to select, upload a shape file so that the polygon can be displayed on the map widget.

### Scenario 1: 

User accesses the map widget drawer, clicks a button to upload a shape file. File uploads and card appears with the name of the file and the option to remove the file (similar to other widgets). 

Users clicks "Preview Map" button and sees a preview of the shapefile on the map.

### Scenario 2:

Matches wireframes:
https://xd.adobe.com/view/314be723-38ea-4f16-acb4-69db36ac71f9-6418/screen/3aab1a4f-2575-4915-a274-3eaa19b3425c/
https://xd.adobe.com/view/314be723-38ea-4f16-acb4-69db36ac71f9-6418/screen/026876b8-374a-4463-bacd-6d7386e401a8/

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by djnunez-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1382?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Option to remove the file not showing after the widget is saved.
