### ISSUE TITLE
BUG Cannot enter a comment in Rate My App - in Edge Browser

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#1389]
![image](https://user-images.githubusercontent.com/101662408/226483181-50e885ed-9e65-443c-984f-875708fd83a2.png)

Can't hit submit after writing in text for Rate My App - button is greyed out both in front end and back end. 

Ma note: I experience the same issue on a MacBook pro in Chrome.

**Comment by tiagograf-AOT** [comment]
Fix confirmed
