### ISSUE TITLE
As an Admin I want to select the person(s) to contact (existing contact) on the  "Who is Listening" widget.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#139]
As an Admin
I want to select the person(s) to contact (existing contact) on the "Who is Listening" widget
So that the public can see who is in charge of this engagement and contact them directly.

Acceptance Criteria

Scenario 1:
Admin has selected "Who is Listening" from the widget selection (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/138)

Scenario 2:
Confirm user interface to the visual design
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/82dbfb0c-1144-4f91-8631-ebc18293bf3b/specs/

Section Header: Who is Listening (+ edit icon = widget name is editable)
Checkbox to "Hide Title" (to hide title on published card)
Drop-down to select previously entered Contacts "Select Existing Contact" & Add this contact" button.
Button "Create New Contact" (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/141)
"Save & Close" and "Cancel" buttons

Scenario 3:
Admin Selects contact from drop-down, Clicks "Add This contact", Contact is added (grey card) and shows on "Who is Listening" Window (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/142)

Scenario 4:
Admin clicks "Save & Close" to save the widget. Widget is created (even if no Contact has been added).

Scenario 5:
Admin clicks "Cancel" to exit. Widget is not created.

Screenshot
![Screen Shot 2022-05-24 at 5.41.55 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/263b95ab-c908-4b21-8d11-d8fd11fcc46a)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/139?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
