### ISSUE TITLE
As a public user, I want to see the survey responses over time.

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1398]
Show the count of responses over time on the public dashboard. Users should be able to toggle between months/weeks to see the count of responses by month/week.

Refer below screen shot:
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/f2497ced-2710-4b4d-97e5-f0859d4ee11a)

**Comment by tiagograf-AOT** [comment]
New endpoint in analytics-api
Integrate front-end with new analytics-api
