### ISSUE TITLE
As a public user, I want to see the overall survey results summary.

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1403]
Show a chart which displays the count of below data points for a survey

1) Survey links sent
2) Surveys completed
3) Responses with comments

Refer below screen shot:
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/7497c736-d1e4-40ac-ace5-76b0e68c0762)

Site visit is added as part of internal dashboard. Could be made available on external dashboard after we have a process to extract that data.

UPDATE:

Change visual data references to 
1) Survey emails sent
2) Surveys completed
3) Project location

![Screenshot 2023-04-24 at 10.14.35 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/80c5bae8-c868-4915-bcd0-44738c1e3450)

**Comment by tiagograf-AOT** [comment]
New ETL task to pull survey emails sent
New ETL task to pull engagement location map
New endpoints for survey counts and location
New map component in the dashboard

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1403?planning-poker) with Zenhub @djnunez-aot @tiagograf-AOT @VineetBala-AOT
