### ISSUE TITLE
As an Admin, I want to add a new contact to "Who is Listening" widget.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#141]
**As an** Admin

**I want** to add a new contact to "Who is Listening" widget

**so that** when the Engagement is published, the public can contact the person in charge of the project.

### Scenario 1: 
Admin has selected "Who is Listening" from the widget selection (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/138), and clicked the "Create New Contact" button.

### Scenario 2: 
Confirm user interface to the visual design
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/ebf42045-3ed1-40f5-b402-cb4d264bb0d5/specs/

### Scenario 3:
The "Create New Contact" panel opens

Section Header: Create New Contact
Add Profile Picture (drag & drop or click to upload)
Input fields for: Name, Role (optional), Phone (optional), Email, Address (optional), 
and Text Area for Bio (Rich Text editor) (optional)
"Save & Close" and "Cancel" buttons

### Scenario 4:
Admin fills in info to add contact and Clicks "Save & close", Contact is added and shows on the "Who is Listening" window. (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/142) 

### Scenario 5:
Admin clicks "Cancel" to return to the "Who is Listening" main window.

### Validation Rules? 

(If yes, list here)

### Screenshot 

![Screen Shot 2022-05-24 at 5.41.25 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/678abe5d-3727-4156-9ec3-687c3094c30c)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/141?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
@marieanik can you make a follow-up card with JUST the profile image part to its own ticket?

**Comment by carlygreenehill** [comment]
Carly's assessment:

LOW PRIORITY

![add who is listening](https://user-images.githubusercontent.com/101662408/197256510-c0ad7b9d-11cc-4102-954d-1dbbc8617523.PNG)
- Who Is Listening looks funny in sentence case. Is that just me? Does "Who is Listening" look better for some reason?
- I think there needs to be more white space between box border and text 

![Capture - success banner](https://user-images.githubusercontent.com/101662408/197256771-23032c81-1130-46c5-ac50-178d86e17e79.PNG)
- suggested for Success banner: Widget successfully created. Proceed to Add Contacts

![Capture - add this contact](https://user-images.githubusercontent.com/101662408/197256944-dfd88994-5386-41e8-bb3a-ebdb057ff9c4.PNG)
- Should read: Add This Contact (capitalize the C)

![Capture - jad found a bug](https://user-images.githubusercontent.com/101662408/197257048-78c087aa-b206-405b-8c33-77f9323b0389.PNG)
- Jad found a bug and is fixing - user gets an error when hits "Save & Close" after Adding a Contact
