### ISSUE TITLE
Add character count to description block + tweak description for the content block

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1414]
As a system admin user, I want to know the number of characters I entered in the description content section so I can easily see how many characters I already have typed in or need to remove.

As a system admin user, I want to know the maximum number of characters I can enter in the description content section so I don't try to save my engagement to learn it.

![Screenshot 2023-03-23 at 10.41.24 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/724a97ef-0e8b-442b-a142-ca7245e8c562)

**Comment by tiagograf-AOT** [comment]
@djnunez-aot character count is 0 when first loading the engagement:

![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/7d19c3cf-ad54-4963-8fbf-d1d7f63ab4ce)
