### ISSUE TITLE
As an Admin, I want to see the Contact added to the "Who is Listening" widget.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#142]
**As an** Admin
**I want**  I want to see the Contact added to the "Who is Listening" widget
**so that** I can see the contacts I added to the widget and confirm I added the information correctly.

### Scenario 1: DONE
Admin has added a Contact, either existing one from the drop-down menu (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/139) OR from Scratch (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/141)

### Scenario 2: DONE
The user interface must follow the visual design as per 
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/c6bcd152-50e3-423e-964f-3ec899fdb037/specs/
Header h3
Name h4

### Scenario 3: SORT OF DONE - SORTING NOT COMPLETE
Admin sees a Grey "card" added to the "Who is Listening" widget panel containing:
Column 1: Move icon (to move the Contact up and down if other Contacts are added.
Column 2: Contact Name, role 
Column 3: Labels and content: Phone, Email, Address, and Bio (truncated to first 100 characters, followed by ellipses)
Column 4: "Edit" and "Delete" icons - **STILL IN PROGRESS**

**Marie Anik's Note: @jadmsaadaot Can you please tweak the design from this (current in Dev):
![Screen Shot 2022-10-25 at 2.06.58 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/2c710982-9c90-4a05-ba06-cd5adaa49201)

To:
![whoislistening.jpg](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/06f35e7a-e74b-45f6-ba33-8b462a6de933)

### Scenario 4: DONE
Admin moves the card above and below other cards, if present, by clicking on the "move" icon and placing the card above or below other cards.

### Scenario 5: DONE
Admin clicks the "edit" icon to go to the "Add Contact" window (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/141). Header now showing as "Edit Contact".

### Scenario 6: NOT DONE OR STARTED
Admin clicks the "Delete Icon" (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/144) If Admin deletes the card, user still present in drop-down "Select Existing Contact".

### Validation Rules

Only two fields are mandatory: Name and email address. Indicate with an *
If no image uploaded, we will have a placeholder icon. (I will provide it soon)

### Screenshot 

(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-24 at 5.44.16 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/b256c75b-bb31-404f-be30-7c9b921fc9d0)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/142?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
Let's be mindful of...

- do we need to keep historical data?
- what happens if Mindy Ming leaves the project (and is no longer listening) and now its Mo Forest?

Can we handle these scenarios by...
- turning off widget once the engagements ends
- generic emails/contacts for "who listened" past tense
-

**Comment by carlygreenehill** [comment]
Increased estimate after discovering the "dragging" task /w sorting would take more effort

**Comment by carlygreenehill** [comment]
All that's left is to ensure that the front end display of the sorted Contacts is complete
