### ISSUE TITLE
Badges to be clickable on survey page and engagement listing pages

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1421]
As a MET system user, I want to access filtered comments by clicking the page on the listing pages so that I can access directly and only the comments relevant to me.

Add filters on the comments page: https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1420

Comments badges are links to filtered comments by status

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1421?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
