### ISSUE TITLE
As an Admin, I want to see the "Who is Listening" widget I added to an Engagement.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#143]
**As an** Admin

**I want** I want to see the "Who is Listening" widget I added to an Engagement

**so that** I know I added this widget and can move it above or below other widgets.

### Scenario 1: 
Admin created a widget and clicked the "Save & Close" button on the widget panel.

### Scenario 2:
Confirm user interface to the visual design https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/64369cc7-ca7d-40c8-b6b7-874a05917540/specs/

### Scenario 3:
Admin sees a grey "card" with the following content on the Engagement window:

Column 1: Move icon (to move the Team Member up and down if other widgets are added.
Column 2: Label (16px bold): Widget Name
Column 3: "Edit" and "Delete" icons

### Scenario 4:
Admin moves the card above and below other cards, if present, by clicking on the "move" icon and placing the card above or below other cards.

### Scenario 5:
Admin clicks the edit button to go to the widget panel (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/139). 

### Scenario 6:
Admin clicks the "Delete Icon". Modal to confirm deletion appears.  
(https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/144)
### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-27 at 2.15.18 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/4732f3c3-13e3-48de-8e40-894928effe57)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/143?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
Re-estimated this card after more information about "dragging" + "sorting" was brought up in Grooming.

**Comment by carlygreenehill** [comment]
Add two "fake" widgets as placeholders??

**Comment by carlygreenehill** [comment]
!!! Let's wait to move this out of QA UNTIL we can test drag & drop functionality. We can test that when there is document widget made.

**Comment by VineetBala-AOT** [comment]
- Admin is able to create multiple widget and drag to re-order them. 
- Both edit a widget and delete a widget is working as expected. 
- All delete icons are made standard to the "x" mark.

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/2a4c4b3e-ab79-4548-a57c-a61f398c1a73)
