### ISSUE TITLE
Update tooltips, labels, and tabs in form.io

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1434]
**Please don't delete the "Validate on" field on the validation tab. I'll provide tooltip for it.**

As a MET system user, I want to have clear labels and tooltips to refer to when I create a survey in form.io so I don't have to look for instructions.

Update the labels and tooltips as below (or here on a word doc: https://bcgov.sharepoint.com/:w:/r/teams/04610/Shared%20Documents/General/tooltips.docx?d=wffbe9b7eba5145ffadd84c759b232fde&csf=1&web=1&e=ffv5Z6)

**for all the items having a "Validate on" section on the "Validate" tab, change the tooltip to:

"Determine when this component should trigger validation. Validate on change will validate when the users click to move to the previous/next page or submit the form. Validate on blur will validate as soon as an answer is entered in the field. For the best experience, we recommend validating on change."

Header 
 

Content > Header (can we make single-line instead of text-area?) 
 

Tooltip >  

Write your header in this section.  

You can preview the header on the right in the “Preview” section. 
 

CSS class > HIDE 
 

Paragraph 

Content > Paragraph Content 

Tooltip >  

Write your paragraph in this section.  

You can preview the paragraph on the right in the “Preview” section. 

 

CSS class > HIDE 

 

Single Line Answer 

Display tab 

Label > Question/Label 

Tooltip >  

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

 

Placeholder 

Tooltip >  

The placeholder is a short hint intended to aid the user with data entry. This text will be displayed in the input field to provide more details on what is expected. For example: for the question/label “Your Birthdate”, the placeholder could be DD/MM/YYYY. 

You can preview the placeholder on the right in the “Preview” section. 

 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details. For example: “Please do not add any personal information.” 

You can preview the tooltip on the right in the “Preview” section. 

 
 

 
 

Tooltip 

Tooltip >  

Add a tooltip to your question/label 

Input Mask 

Tooltip >  

An input mask helps the user with input by ensuring a predefined format. 

9: numeric 

a: alphabetical 

*: alphanumeric 

For example: for the question/label “Postal Code”, the input mask could be: A9A 9A9 

Allow Multiple Masks 

Tooltip >  

Allows the user to enter data in two or more different formats.  

For example: the question/label “Postal Code/Zip” could have the input masks of: A9A 9A9 and 99999 

Allow Spellcheck > Can we set to “True” and HIDE? 

 

Validation tab 

Required 

Tooltip >  

Will make this question mandatory. A required field must be filled in before the form can be submitted. 

Custom Error Message  

Tooltip > 

Customize the error message displayed when the content entered does not match the requirements for this filed such as Input Mask, Minimum and Maximum Characters or Words Count. 

For example: The minimum number of characters for a field has been set to 10. User enters 7 characters. The Custom Error Message could be “Please enter a minimum of 10 characters.” 

Minimum Length > Minimum Character Length  

Tooltip >  

This is the minimum number of characters required for this field. 

Maximum Length > Maximum Character Length  

Tooltip >  

This is the maximum number of characters required for this field. 

Conditions tab > As is 

 
 

 
 

 
 

Multiple Lines Answer 

 

Display tab 

Label > Question/Label 

Tooltip >  

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

Placeholder 

Tooltip >  

The placeholder is a short hint intended to aid the user with data entry. This text will be displayed in the input field to provide more details on what is expected. For example: for the question/label “Your Birthdate”, the placeholder could be DD/MM/YYYY. 

You can preview the placeholder on the right in the “Preview” section. 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details. For example: “Please do not add any personal information.” 

You can preview the tooltip on the right in the “Preview” section. 

Rows > As is 

Tooltip 

Tooltip >  

Add a tooltip to your question/label. 

Auto Expand 

Tooltip >  

This will make the Text Area auto expand its height as the user is typing into the area so the entire content remains visible. 

Allow Expand 

Tooltip >  

This will make the Text Area auto expand its height as the user is typing into the area so the entire content remains visible. 

Allow Spellcheck > Can we set to “True” and HIDE? 

 
 

Validation tab 

 
 

Required  

Tooltip >  

This will make this question mandatory. A required field must be filled in before the form can be submitted. 

Custom Error Message  

Tooltip >  

Customize the error message displayed when the content entered does not match the requirements for this filed such as Input Mask, Minimum and Maximum Characters or Words Count. 

For example: The minimum number of characters for a field has been set to 10. User enters 7 characters. The Custom Error Message could be “Please enter a minimum of 10 characters.” 

Minimum Length > Minimum Character Length  

Tooltip >  

This is the minimum number of characters required for this field. 

Maximum Length > Maximum Character Length  

Tooltip > 

This is the maximum number of characters required for this field. 

Minimum Word Length > As is 

Maximum Word Length > As is 

Conditional tab > Change to “Conditions” 
 

Postal code 

Keep? TBD 

If we do,  

Tooltip >  

Pre-populate label with “Enter the first 3 letters/digit of your postal code. 

 

Radio Button 

Display tab 

Label > Question/Label 

Tooltip > 

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details. For example: “Please select only one option.” 

You can preview the tooltip on the right in the “Preview” section. 

 
 

Tooltip 

Tooltip >  

Add a tooltip to your question/label. 

Inline Layout > Hide 

 

Values tab 

Default Value 

Tooltip > 

Enter your labels for this question below and select here any options you want pre-selected to true (already selected). 

Values > Labels and Values 

Tooltip > **remove the tooltip for this and add with each column 

(Table) Labels 

Tooltip >  

Labels are the text that appears next to the radio buttons on the form (the possible “answers”.) 

(Table) Values 

Tooltip > 

Values are text submitted with the form data. They won’t appear on the form. Values will be automatically generated when you enter the labels. They are editable. 

Shortcut > HIDE column ** if impossible, can we make it narrower? If not possible, let me know and I’ll write a tooltip 

 

Validation tab 

Custom Error Message  

Tooltip >  

Customize the error message displayed when the content entered does not match the requirements for this filed such as Input Mask, Minimum and Maximum Characters or Words Count. 

For example: The minimum number of characters for a field has been set to 10. User enters 7 characters. The Custom Error Message could be “Please enter a minimum of 10 characters.” 

Minimum Length > Minimum Character Length  

Tooltip >  

This is the minimum number of characters required for this field. 

Maximum Length > Maximum Character Length  

Tooltip >  

This is the maximum number of characters required for this field. 

Conditional tab > Change to “Conditions” 

 

 
 

 
 

Checkboxes 

 

Display tab 
 

Label > Question/Label 

Tooltip > 

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details. For example: “Please select up to three options.” 

You can preview the tooltip on the right in the “Preview” section. 

Tooltip 

Tooltip >  

Add a tooltip to your question/label. 

Inline Layout > Hide 

 

Values tab 

Default Value 

Tooltip > 

Enter your labels for this question below and select here any options you want pre-selected to true (already selected). 

Values > Labels and Values 
 

Tooltip > ***remove the tooltip for this and add with each column 

(Table) Labels 

Tooltip >  

Labels are the text that appears next to the radio buttons on the form (the possible “answers”.) 
 

(Table) Values 

Tooltip > 

Values are text submitted with the form data. They will not appear on the form. Values will be automatically generated when you enter the labels. They are editable. 
 

Shortcut > HIDE column ** if impossible, can we make it narrower? If not possible, let me know and I’ll write a tooltip 
 

Validation tab 

Custom Error Message  
 

Tooltip >  

Customize the error message displayed when the content entered does not match the requirements for this filed such as Input Mask, Minimum and Maximum Characters or Words Count. 

For example: The minimum number of characters for a field has been set to 10. The user enters 7 characters. The Custom Error Message could be “Please enter a minimum of 10 characters.” 
 

Minimum Length > Minimum Character Length  

Tooltip >  

This is the minimum number of characters required for this field. 

Maximum Length > Maximum Character Length  

Tooltip >  

This is the maximum number of characters required for this field. 

Conditional tab > Change to “Conditions”  
 

Content 
 

Display tab 

Label > Why is this here? Doesn’t show anywhere... Remove? 

What is Refresh on Change??? 

Hidden > remove 

Modal Edit > remove 
 

API tab > Remove 

 

Conditional > Rename “Conditions” 

Remove Advanced and json sections 

 
Logic tab > Remove 

Layout tab > Remove 

 
 

HTML 

 
 

Display tab 
 

Label > Why is this here? Doesn’t show anywhere... Remove? 
 

Hidden > remove 

Modal Edit > remove 
 

API tab > Remove 

 

Conditional > Rename “Conditions” 

Remove Advanced section 

 
Logic tab > Remove 

Layout tab > Remove 

 

 

Drop-Down (Select list component 
 

Display tab 

Label > Question/Label 

*Please delete placeholder text in the Label input field (currently Select List) 

Tooltip >  

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

Placeholder 

Tooltip >  

The placeholder is a short hint to aid the user with data entry. This text will be displayed in the input field to provide more details on what is expected. For example: in the drop-down for “Select your favourite colour”, you could put “Select one colour” 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details.  

You can preview the tooltip on the right in the “Preview” section. 

Tooltip 

Tooltip >  

Add a tooltip to your question/label 
 
Data tab > rename “Values” 

Multiple values 

Tooltip > 

Will let the respondent enter more than one selection. 

Default value  

Tooltip > 

Select which option will be selected by default. 

Validation tab 

Validate on 

Tooltip > Determine when this component should trigger validation. Validate on change will validate when the users click to move to the previous/next page or submit the form. Validate on blur will validate as soon as an answer is entered in the field. For the best experience, we recommend validating on change. 
 

Required  

Tooltip >  

Will make this question mandatory. A required field must be filled in before the form can be submitted. 

Custom Error Message  

Tooltip > 

Customize the error message displayed when the content entered does not match the requirements for this field such as Input Mask, Minimum and Maximum Characters or Words Count. 

Conditions tab > As is 

 
 Survey 

Display tab 

Label > Question/Label 

Tooltip > 

Write your question or label in this section.  

You can preview the question/label on the right in the “Preview” section. 

Label Position > Set to top and remove 

Description 

Tooltip >  

The description is text that will appear below the input field. You can use this text to add details. For example: “Please select the option that applies most.” 

You can preview the tooltip on the right in the “Preview” section. 

Tooltip 

Tooltip >  

Add a tooltip to your question/label. 

Custom CSS > Hide 

Tab index > Hide 

Hide all the checkboxes (hidden, hide label etc.) 

Data tab > rename “Values”  

Default Value 

Tooltip > 

This will be the value for this field, before user interaction. 

Persistent > Remove this section and all sections below 

Validation tab 

Validate on 

Tooltip > Determine when this component should trigger validation. Validate on change will validate when the users click to move to the previous/next page or submit the form. Validate on blur will validate as soon as an answer is entered in the field. For the best experience, we recommend validating on change. 

Required  

Tooltip >  

Will make this question mandatory. A required field must be filled in before the form can be submitted. 

Custom Error Message  

Tooltip > 

Customize the error message displayed when the content entered does not match the requirements for this field such as Input Mask, Minimum and Maximum Characters or Words Count. 

Conditional tab > Change to “Conditions”

**Comment by carlygreenehill** [comment]
Given a bigger value because:
- improves staff training
- high report rate in ux testing sessions (users found the tooltips particularly unuseful)

**Comment by djnunez-aot** [comment]
Everything is completed except content component that was moved to https://github.com/bcgov/met-public/issues/2027

**Comment by VineetBala-AOT** [comment]
Please verify the below:
- Paragraph Content -- tooltip needs to be corrected
- Postal code is kept so I believe we need to update the tooltip
- On Radio question there is a unwanted character, please refer below screen shot:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEV4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--debecb5f592a26fa1e1fd42c27711a39f6659215/image.png)
- Same with check box
- Checkbox Minimum Length > Minimum Character Length - Tooltip >This is the minimum number of characters required for this field.
- Checkbox Maximum Length > Maximum Character Length - Tooltip >This is the maximum number of characters required for this field.
- Checkbox Conditional tab > Change to “Conditions”
- Drop-Down (Select list component) - Display tab- Label > Question/Label - *Please delete placeholder text in the Label input field (currently Select List)
- Drop-Down (Select list component) - Custom Error Message - Tooltip > Customize the error message displayed when the content entered does not match the requirements for this field such as Input Mask, Minimum and Maximum Characters or Words Count.
- Survey - Description - Tooltip > The description is text that will appear below the input field. You can use this text to add details. For example: “Please select the option that applies most.”
- Survey - on values tab: Default Value - Tooltip > This will be the value for this field, before user interaction.
- Survey - Tooltip > Customize the error message displayed when the content entered does not match the requirements for this field such as Input Mask, Minimum and Maximum Characters or Words Count.

**Comment by TayaLee8** [comment]
**MA review:**

1. Single line answer/Radio button/Checkboxes/Drop down components > Description component > Tooltip:
*"The description is text that will appear below the input field. You can use this text to add details. For example: “Please do not add any personal information.” You can preview the tooltip **(description?)** on the right in the “Preview” section."*

^change word 'tooltip' to 'description'?


2. Checkbox component > Validation tab: Do we still want minimum/maximum checked number/error message fields? This was not verified in the above acceptance criteria but remains in the component. 

**Please fix:**

Radio button component > 'Conditional' tab change to 'Conditions'

Content component > 'Addons' should be 'Add-ons'

Drop down component > Remove placeholder text in the Question/Label field 
Drop down component > Please add the placeholder field with changes indicated in MA's acceptance criteria above
Drop down component > 'Select List items' table should be consistent with the other components that have this attribute. See Checkbox component for reference/example.
