### ISSUE TITLE
Change site Logo based on Tenant

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1437]
As a Super Admin i want to be able to upload a logo to a Tenant so that the site has the branding I want.

**Comment by VineetBala-AOT** [comment]
Verified, the sites are showing up different branding based on tenant. Links used to verify are as below:
https://met-web-dev.apps.gold.devops.gov.bc.ca/eao
https://met-web-dev.apps.gold.devops.gov.bc.ca/emli
