### ISSUE TITLE
Identify Tenant Instance based on URL

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1438]
url must be matched to a specific tenant e.g.:

met.gov.bc.ca/gdx - only shows gdx data
met.gov.bc.ca/emli - only shows emli data

what happens if only the generic site is accessed (met.gov.bc.ca tenant selection)?

Check the feasibility of not having a tenant id in the url to support eao.met.gov.bc.ca

**Comment by saravanpa-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1438?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @tiagograf-AOT @VineetBala-AOT
