### ISSUE TITLE
As an Admin, I want to confirm when I delete a widget or item in a widget.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#144]
**As a** Admin

**I want** I want to confirm when I delete a widget or item in a widget

**so that** I don't delete something inadvertently

### Scenario 1: 
Admin clicks a "delete" icon and sees a Modal:
- h3: Delete <item name>
- Content: Please confirm you want to delete (item name) from this (widget/survey/Engagement). 
- "Confirm" button: Deletes the item
- "Cancel" button: item is not deleted

### Scenario 2:
Confirm user interface to the visual design
https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/e355ae52-998f-4cd0-89d7-54ef5edab5ad/specs/

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-19 at 1.58.20 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/95bbec1e-7640-47f7-a93b-15209c052408)

**Comment by carlygreenehill** [comment]
Saravan says "make this card more generic."

**Comment by jadmsaadaot** [comment]
For the purpose of deleting widget items. I feel this doesn't play well with the 'Save & Close' button. If someone pressed delete on a widget item, saw the model, or pressed confirm but did not press 'save & close' no deletion will happen. Which feels weird to me

**Comment by jadmsaadaot** [comment]
@marieanik @saravanpa-aot  could we please discuss this further for the above concern

**Comment by tiagograf-AOT** [comment]
Checked as a team and this was already implemented, more discussion might be needed in a separated card
