### ISSUE TITLE
Delete Rejected Comments (PI) after engagement is closed

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1441]
Comments containing PI (rejected comments) should be deleted after the engagement is closed.

A scheduled job that will check for closed engagements after 14 days (make it configurable) and REDACT the comments that were rejected. Replace comment text with "[Comment Redacted]"

**The job MUST also, find the element in the original submission JSON and redact value in that field (with same value. as above. "[Comment Redacted]").**

If flag "Had Threat" is checked, DO NOT redact the comment.

**Comment by tiagograf-AOT** [comment]
Do we need to prevent people from approving a previously rejected comment?

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1441?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by saravanpa-aot** [comment]
Probably it will be a good idea to track which comment got redacted/deleted for the future purposes... 
may be we keep the logs/tracks in a separate table ..Main motivation is for future audit purposes..
once we delete a comment , we might loose the history and probably hard to track it back

**Comment by tiagograf-AOT** [comment]
We are not deleting any comments, just redacting the text, but i agree with you, maybe we should have a flag for redacted comments (IsRedacted)?

**Comment by tiagograf-AOT** [comment]
After the discussion with Saravann about having logs we decided to create another ticket to handle Auditing of records #1468.

**Comment by tiagograf-AOT** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1441?planning-poker) with Zenhub @jadmsaadaot
