### ISSUE TITLE
Shape file not showing on map widget

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1446]
[https://app.zenhub.com/files/480383041/c71ecc85-fc90-4ab8-a4f8-879779c6965d/download](https://app.zenhub.com/files/480383041/c71ecc85-fc90-4ab8-a4f8-879779c6965d/download)

**Comment by carlygreenehill** [comment]
@djnunez-aot @VineetBala-AOT   --- is this bug still a problem or did some of our other work fix it?

**Comment by carlygreenehill** [comment]
We think it was just one corrupted shapefile. We've tried other shapefiles since and they all work. Closing as fixed!
