### ISSUE TITLE
form.io - Validate user entries when they click "next" or "submit"

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1491]
Currently, the question/answers turn red as soon as you check one box (when three are required). Validation should be done when they navigate away from the current page.![Screenshot 2023-04-11 at 3.50.29 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/5f3a911a-7af4-4afb-9624-f6e38747385b)

**Comment by jadmsaadaot** [comment]
This exists at component level not at page level. The above issue happens also on singlge. Formio components by default either validate on change or on blur (when you click away from the component). There isn't a default formio way to stop components from validating until the next button is pressed.

**Comment by jadmsaadaot** [comment]
This exists at component level not at page level. The above issue happens also on singlge. Formio components by default either validate on change or on blur (when you click away from the component). There isn't a default formio way to stop components from validating until the next button is pressed.

**Comment by jadmsaadaot** [comment]
To fix  this a "Validate On" select was added in the validation tab that has to be changed to blur for it to work
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/b8a7b376-379d-4975-9ff6-85184d01daf6)
