### ISSUE TITLE
Share your thoughts not disabled on preview for closed status

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1503]

**Comment by tiagograf-AOT** [comment]
@VineetBala-AOT i think we do this on purpose so when previewing the engagement the staff user can also preview the survey.

**Comment by carlygreenehill** [comment]
@TayaLee8 @VineetBala-AOT  --- can you please check to see if this is still happening in any of our environments?

**Comment by TayaLee8** [comment]
Not happening in DEV or TEST:
![image](https://github.com/bcgov/met-public/assets/122818332/1d4b825b-14a5-49e2-b357-7057675af039)

DEMO looks like this: 
![image](https://github.com/bcgov/met-public/assets/122818332/166f7fe3-a427-4c2f-90ec-eec38f4424a4)
