### ISSUE TITLE
Comments not reviewed yet showing on the report.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1527]
Seen in Dev and Demo.

Comments are still pending review but already showing up in the report. 

For example, https://met-web-dev.apps.gold.devops.gov.bc.ca/eao/engagements/132/dashboard has 2 submissions of 3 comments each. One submission is still pending review but the comments are already showing in the report.

**Comment by VineetBala-AOT** [comment]
Verified, only the approved comment is showing on the report.

**Comment by marieanik** [comment]
@VineetBala-AOT Let's chat. I looked at the Sierra Terra and still see the pending comments in the report.
