### ISSUE TITLE
User Calendar feature - Public Dashboard

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1536]
Tablet view is  a bit wonky...
![Screenshot 2023-06-05 at 2.39.56 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/077b424a-8d82-46f2-a507-2a6702a2139c)

and the Mid-size screen date fields are squished. 
The calendar icon should be #494949
The "double-selection" button monthly/weekly should have a height of 34px and weekly should be on the left, then monthly on the right.

![Screenshot 2023-06-05 at 4.04.21 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/7324bff4-e8f9-40dc-93ad-eb2c1909e5e4)

As a user, I would like to see a calendar function to the left of the monthly/weekly report in the live activity/engagement box on the public dashboard so that I can select a date range to view the data for a specific period of time.
https://xd.adobe.com/view/1a3f8b30-4522-4228-b44b-c5625ccd4276-4f6c/

![Screenshot 2023-04-24 at 11.56.11 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/7110a26f-1139-4769-9ae2-cb8f4d641bbe)

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1536?planning-poker) with Zenhub @djnunez-aot @tiagograf-AOT @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Add calendar to pick date range
Add date range filter to endpoints
