### ISSUE TITLE
Header/Read Comments/Return to report Button- Public user dashboard

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1543]
As a user, I would find it extremely convenient if I could hit the 'read comments' button in the upper right area of the layout so that the user could read comments on a separate page as well as go back to the comments page from hitting the 'return to report' button at the top right of the comments page.

![Screenshot 2023-04-26 at 8.56.37 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/60119ca8-7ad2-4c8e-b52d-1a5fb12d8c46)

![Screenshot 2023-05-25 at 9.46.30 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/52653145-1b64-43e8-84a3-aa72e391104b)

**Comment by marieanik** [comment]
*Make sure to capitalize the R on the "Return to Report" button.

**Comment by marieanik** [comment]
I'm not sure where this is applicable. Let's ask Ian when he is back on Monday.
