### ISSUE TITLE
X to remove filters (Home page)

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1548]
User should be able to remove filtered text from text boxes on homepage. As a user I would like to refresh the selection of words available by hitting the x icon as seen in the box to the left. It would be best if this option was available in all boxes.

![Screenshot 2023-04-28 at 3.25.20 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/80a59d13-2da0-401d-b670-0ff4bb23ded3)

**Comment by marieanik** [comment]
Closing as not doable for this type of filed: "if we were to add the x markers we would have to change the dropdowns for Status & Project Type like the one for Engagement name"
