### ISSUE TITLE
MET public home - Changing text on buttons 

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1581]
As a user I would like to feel more involved with issues at stake by hitting a "Take action" button instead of a "share your thoughts" button. This choice of words makes me seem more involved in community concerns.
Other examples of CTA text:
"Get started"
"Discover now"
"Explore further"
"Find out how"
"Take the next step"
"Uncover the details"
"See for yourself"
"Dig deeper"
"Start your journey"

![Screenshot 2023-05-09 at 1.19.45 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/94fc48de-2079-4cea-ba9b-92285bfeef70)

**Comment by marieanik** [comment]
After talking to Josh, we decided to keep the buttons as is.
