### ISSUE TITLE
Selecting sections to add the subscribe widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1601]
As a MET system user, I want to select what section to include on the form so that I can customize it according to my needs. 

User selects the subscribe widget from the widget selection list. On the drawer for that widget, the user sees a description and two options.

Description (TBC): The email list will collect email addresses for a mailing list. A "double-opt-in" email will be sent to confirm the subscription. Only the email addresses that have been double-opted-in will be on the list. 

The form sign-up will open the pre-defined form. The text and CTA for both are customizable. 

Buttons: "Email List" "Form Sign-up"

& "Close"

ACCEPTANCE CRITERIA
- https://xd.adobe.com/view/c21bb61a-1be0-4cef-a3b0-ea21918926d8-9748/screen/7979ba05-2e61-408e-a24d-9fdce017d4b3/

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1601?planning-poker) with Zenhub @aforde-aot @jadmsaadaot @VineetBala-AOT @djnunez-aot @saravanpa-aot

**Comment by VineetBala-AOT** [comment]
@djnunez-aot , description needs to be fixed.

**Comment by VineetBala-AOT** [comment]
Verified.
