### ISSUE TITLE
Upload documents to document widget

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1617]
As a MET system user, I want to upload documents in the Documents widget through an upload/drag-and-drop so that I can make them available to the public.
Please see first link below:

2. As a user willing to share documents to the MET platform I would like to have the options of renaming the content that is either uploaded as separate documents, adding a link to the document and adding it to a folder. This way I can customize labels on content that will be shown on my engagements.
Please see the second link below:

3. As a user willing to share documents to the MET platform I would like to have the option of uploading a document and also know when the document has been uploaded successfully.This way I will know/ have the reassurance that the document is now on the MET platform.
Please see the third link below:

https://xd.adobe.com/view/5d4427ac-a66c-4874-bf50-975cc538b28f-0817/screen/b399c13d-4866-49ba-8de8-f412fa6f5513/

https://xd.adobe.com/view/5d4427ac-a66c-4874-bf50-975cc538b28f-0817/screen/e82f7b31-d745-4cb5-bcea-fb70d939a143

https://xd.adobe.com/view/5d4427ac-a66c-4874-bf50-975cc538b28f-0817/screen/b399c13d-4866-49ba-8de8-f412fa6f5513/
Below is a link referring to XD/Github sources that may help as well as the uploaded PNG asset

https://github.com/danielm/uploader
https://github.com/kartik-v/bootstrap-fileinput

![Screenshot 2023-05-26 at 4.27.19 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/d4ee0d3c-b3e0-4b78-99ce-097b1ca72903)

![Screenshot 2023-05-26 at 4.38.09 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/c0d501b9-4cf3-4350-83a8-927a622ff8bf)

![Upload cloud.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/c5af6a5c-d4ff-4aa8-b7d6-c936a5c642ca)
1![Screenshot 2023-05-29 at 11.42.38 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/7e5f76c9-2da8-4aae-a5c7-9ee64b222130).

**Comment by VineetBala-AOT** [comment]
We might have to consider how we store the files in a multi-tenanted environment on S3. Should it be in different buckets.
