### ISSUE TITLE
As an Admin, I want to add a link to a document (EPIC) to the Document widget.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#162]
**As an** Admin

**I want** to add a link to a document to the Document widget

**so that** the public can access the relevant documents from EPIC directly on the Engagement

### Scenario 1: 
Admin sees the "Documents" panel, clicks the "Add Document" button, sees the Add Document panel.

### Scenario 2:
Admin sees an input field "Document Link" (EPIC), enters the link in the input field.

Admin adds a display name for the document

Admin clicks "Save & Close" to save the Document link & name. 

Document can be moved up and down and added/removed from folder.

### Scenario 3:
Admin clicks "Cancel" to exit. The document is not added to the widget.

### Scenario 4:
Confirm user interface to the visual design
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/b7897f6a-60ec-43c2-9bd0-4b089861032f (Add Document button)
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/04a0dba1-8b06-47e6-824d-917b62f2de1b/specs/ (Add Doc panel)
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/d3c98c48-7eed-4f2e-b395-ff0539605067 (View Uploaded Doc)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-27 at 2.38.43 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/d1ce1c16-646e-4d54-9480-f7dd18498609)
![Screen Shot 2022-05-27 at 4.10.33 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/649eebf8-c4f7-41b6-a476-47929d0442b8)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/162?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by carlygreenehill** [comment]
![image](https://user-images.githubusercontent.com/101662408/204644552-08df8cd3-4353-4a10-adc6-4f3d6c7c12fb.png)

There's no "success" notification when I hit Save & Close after aka nothing happens. However, when I go to preview that engagement, I can see the Documents widget and linked documents.
