### ISSUE TITLE
As an Admin, I want to create folders in the Documents widget so I can classify my documents.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#163]
**As an** Admin

**I want** to create folders in the Documents widget so I can classify my documents

**so that** it is easier for the public to find them on the Engagement page.

### Scenario 1: 

Confirm user interface to the visual design
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/b7897f6a-60ec-43c2-9bd0-4b089861032f,
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/d3c98c48-7eed-4f2e-b395-ff0539605067
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/19bbac75-6142-4efb-b5b7-1c29f85b4e87/specs/

### Scenario 2:
Admins Selects document widget from the widget selection panel, clicks "Create Folder" button, adds folder name, clicks "Submit" button. Folder is saved and visible on the page. Folder name is editable and can be moved up or down.

### Scenario 3:
Admins Selects document widget from the widget selection panel, clicks "Create Folder" button, clicks "Cancel" button. Folder is not saved. Admin returns to Documents panel.

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)
![Screen Shot 2022-05-27 at 2.38.43 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/52c992e9-765b-406c-a90a-aa3e7bda852b)
![Screen Shot 2022-05-27 at 5.00.06 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/433fda1a-d405-45ea-aad6-e8b0408324e6)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/163?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
