### ISSUE TITLE
Replace Redash "what we heard" report with the new custom dashboard

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1643]
- Change link on the view report action on engagement and survey listing page
- Closing email should send the link to new dashboard
- Internal users should be able to access the dashboard while the engagement is live
- Export to pdf button should be visible for public users
- Dashboard on home page when we click on an engagement except for upcoming needs to be from the new dashboard.

**Comment by marieanik** [comment]
We should show comments as they are approved and only show the dashboard after the engagement is closed (at least for the EAO version. Not sure about EMLI/GDX). We should email the link to the dashboard when the engagement closes and think we should have the pdf button for the public.
@carlygreenehill can you confirm this? ^^

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1643?planning-poker) with Zenhub @saravanpa-aot @VineetBala-AOT
