### ISSUE TITLE
Email Updates on Engagement Publish (Subscribed)

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1646]
As a Citizen, I want to be notified when an engagement is published in MET so that I receive updates about the projects I subscribed to.

*Back-end task

Acceptance Criteria:

When publishing an engagement, send an email to all users that subscribed to MET (Email template to be provided)

**Because there is some disagreement on how Subscribe widget should function, dev team is going to trial two options. This is the first, where a public user can subscribe for updates from an entire instance of MET eg. EAO, get email notification on ANY new engagement.

***We'll slowly trial and add in new rules. Examples of rules that _may_ come in future
- If there are multiple updates on an Engagement Page within (3) consecutive days, only one update email should be sent
- Public user ONLY wants to receive updates on a specific Project (so this would include new engagement pages on different works, like amendments)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1646?planning-poker) with Zenhub @saravanpa-aot @VineetBala-AOT @djnunez-aot @tiagograf-AOT
