### ISSUE TITLE
Add Role gives Error

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1647]
During the new user registration flow, when granting the "Team Member" access the following error message is displayed:
![image.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/6e8d4437-2ca4-42b4-b8e8-98062c5eca7b)

Expected:
The system would automatically grant the required "Viewer" role if not present already.

**Comment by VineetBala-AOT** [comment]
Verified, the error message no longer appears. We have a separate ticket to handle "Viewer" role. Currently the user is assigned the selected role.
