### ISSUE TITLE
Adding a Video Widget to en engagement - Internal

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1655]
As a Engagement Specialist, I would like to add a video so that I can better explain the engagement information to the public.

Acceptance Criteria:

New Video Widget
Staff user adds a description & uploads a video

Please see links below:
https://xd.adobe.com/view/5d4427ac-a66c-4874-bf50-975cc538b28f-0817/screen/8489024d-221f-4b5b-b950-912907a1780e/
https://xd.adobe.com/view/5d4427ac-a66c-4874-bf50-975cc538b28f-0817/screen/3cb48359-7911-478e-8ad0-dd684ba9b88b/

**Comment by tiagograf-AOT** [comment]
notes from spike ticket:

We can stream from both s3 and multiple platforms (Youtube, facebool, vimeo, etc.) using npm react-player. We just pass the url. For s3 the videos need to be public, if not we can generate a signed url via the backend that is authenticated to stream the video

**Comment by VineetBala-AOT** [comment]
Verified, user is able to add a video widget
