### ISSUE TITLE
Spike: Localize the text in the app

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1680]
**How much effort is required to do this?**

We need to make the text in the app customized depending on the ministry

Towards that end:
All the text in the app should be localized and accessed from one constant file. Env variables can be used to customize some of the text depending on the ministry.

**Comment by djnunez-aot** [comment]
Could we do this with constants in the application?

**Comment by jadmsaadaot** [comment]
We can use the i18next and react-i18next libraries. We can add an en.js under public/locales and load it directly or we can fetch it from the backend which can host it or fetch it from an S3:

examples:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/5c0de8ae-f5b5-4106-9d2e-4d7956ae104c)

In app.js:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/0ee88662-76d3-4d7a-b787-08a1651cd37a)

example if we are fetching our text file from an S3:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/5b9cf5a3-04f4-4192-8104-e52b6bda28df)

example en.js file:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/0216e716-84c9-4fd5-b195-abf14a0bf2d1)

example page:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/9e21ac5d-18d1-4e6f-9a60-2447bf47397e)

**Comment by jadmsaadaot** [comment]
This task is an 8 to 13 pointer. We need to install and use the libraries and make sure they work. If we are fetching from an S3 bucket this tilts it to the more complex estimation. 

and finally the easy but rigorous part is replacing all the text in the app.

**Comment by jadmsaadaot** [comment]
installations needed:
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/70dc0ce5-bafe-4e8e-ad36-a85e14f49bcb)

**Comment by saravanpa-aot** [comment]
I think its fair to assume that we will keep the en.json along with source code itself..
Love the idea of s3 ,but we will do that for the second iteration of the task..
how will the code look for local resources?

**Comment by jadmsaadaot** [comment]
@saravanpa-aot much easier if we have it locally, in that case ignore the App.tsx changes and the backend resource and we just do this:

![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/0a9ec6d3-39dd-4fc8-b390-6997bacff72d)

![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/bf2b327d-d51f-4443-9d4c-f5fd32aff3fb)
