### ISSUE TITLE
Custom Engagement Slug

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1681]
As a Engagement Specialist I want to generate a shorter and more descriptive engagement url so that the public can easily relate the url to the engagement.

example:

Engagement: Kamloops Quarry
<domain>/kamloops-quary instead of <domain>/engagement/4/view

Acceptance Criteria:

Suggested path should be generated and unique. Created from the engagement name Sunflower Gold mine = sunflower-gold-mine
If URLm already exist, add the next numeral after: sunflower-gold-mine-2, sunflower-gold-mine-3
Path should be lower case only and separated by hyphens
User should be allowed to change the path/name.
Update links to use new route.

![custom-URL.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/18520f2d-b3ac-48da-8fc5-09584a67daa4)

**Comment by tiagograf-AOT** [comment]
library for generating custom name/url: https://pypi.org/project/python-slugify/

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1681?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Verified:
Generated path is in lower case and separated by hyphens. For example:
https://met-web-dev.apps.gold.devops.gov.bc.ca/eao/qa30-test-engagement-slug-1

If URL already exist, the next numeral is added after the default URL. For example:
https://met-web-dev.apps.gold.devops.gov.bc.ca/eao/qa30-test-engagement-slug-1-1
https://met-web-dev.apps.gold.devops.gov.bc.ca/eao/qa30-test-engagement-slug-1-2

User is able to change the path/name and the existing public links can be accessed using the slug URL.

**Comment by VineetBala-AOT** [comment]
Verified:
- Link on home page is slug URL if existing

Observation:
- Link sent in rejected email needs to be updated to new slug URL
- Link sent in subscription email needs to be updated to new slug URL
- Link for the survey result on submission email needs to be updated
- After submission it navigates back to home page, earlier it used to be on the engagement view page

**Comment by VineetBala-AOT** [comment]
Links on the email will be changed as part of the ticket https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1791
