### ISSUE TITLE
Homepage Input box misalignment

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1682]
As a user using the MET platform I would like to have all input boxes aligned, following basic design principles.

![Screenshot 2023-06-01 at 11.10.09 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/ad5dbdbb-9148-42d6-ae35-67c6d0d68032)

**Comment by djnunez-aot** [comment]
<img width="1054" alt="image" src="https://github.com/bcgov/met-public/assets/103138766/a5f35cac-2f47-4bbe-aed7-4497e2c3da40">

seems like this is fixed
