### ISSUE TITLE
Reviewer role - View/access to information

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1685]
MA note:
I tested with EAO staff. 
Home page is good.
Engagement page is good but we should add the "View Survey" option in the action drop-down
Survey page shows all the surveys. It should only show the surveys attached to the engagements they are assigned to.

This is to define what the Reviewer users view when in MET: 
Let's keep it simple.
They should only see the engagements they are assigned to. 
If we could only show the Engagement page with the engagement they are assigned to, that would be best. 
No access to User Management, Feedback tool etc

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1685?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by VineetBala-AOT** [comment]
Engagement page now has the "View Survey" option in the action drop-down for draft engagements. 

For open engagements reviewer now has the "View All Comments" option in the action drop-down but user should be restricted to approve/reject comment which will be handled as a separate ticket:
https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1753

Survey page shows all the surveys. It should only show the surveys attached to the engagements they are assigned to. This will be handled as part of the ticket 
https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1748

**Comment by marieanik** [comment]
Closing and created https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1759 to deal with survey/comments access for reviewer role.
