### ISSUE TITLE
Public user selects subscription to project or everything

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1690]
Related to #1601 

*This card has some back end changes, and some UI

As a member of the public, I want to be able to select if I want to receive updates from this project?/engagement or from everything at EAO/GDX. (Subject to change for EAO, must be editable per instance)

User clicks the link to register to the mailing list,
Sees a modal with the following content:

Header: Sign Up for Updates
Sign up to receive news and updates on public engagements.

Please choose your preferred email update option:

radio: I want to receive updates for (project name) only
radio: I want to receive updates for all the projects at the Environmental Assessment Office

Personal information (your email address) is collected under Section 26(c) of the Freedom of Information and Protection of Privacy Act, for the purpose of providing content updates and future opportunities to participate.

If you have any questions about the collection, use and disclosure of your personal information, please contact the Director of Digital Services at Sid.Tobias@gov.bc.ca.

Checkbox: I agree to the terms and conditions above.
Input Field: Email Address

![sigu-up-for-updates-modal.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/a9dff002-a20d-40a3-89ae-2b79a1fa3bcb)

User submits and receives a confirmation email (currently https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1046 but will have a new task to edit text when ready)

ACCEPTANCE CRITERIA
- Need to store the data that the user (email) selects

This ticket DOES NOT include the Rule Set aka "Define trigger points -- what should trigger an update in Scenario 1 vs Scenario 2?" Such as... standard rule set as part of MET, can be modified by ministry. Cronjob will also be part of the work w/ ruleset.

EAO Rules: 
- How often are the emails sent? Weekly, monthly?
- Just MET updates? Not EPIC updates, right?

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1690?planning-poker) with Zenhub @jadmsaadaot @aforde-aot @saravanpa-aot @VineetBala-AOT @djnunez-aot
