### ISSUE TITLE
A user can validate their email address to access a survey

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#17]
A user can validate their email address so they can access a survey.

**Acceptance criteria**

Scenario 1:
User clicks a link to access the survey link, sees the "verify email" modal:

Header: Verify your email address
Text: To provide you with the best experience possible, we require you to validate your email address. (i icon, content tbd)

You will receive a link to access the survey at the email address you provide.
Box: T&C (TBC)
Checkbox: I agree to the Terms and Conditions above.
Input:
Email address

Buttons: "Cancel" & "Submit"

Scenario 2:
User adds their email address and clicks "Submit".

Modal:
Header: Thank you
Text: We sent a link to access the survey at the following email address:
<email address provided>
Bold Text: Please click the link provided to access the survey. 
The link will be valid for 24h.

Button: "Close"

User returns to Engagement page

Scenario 3:
User adds their email address and clicks "Submit".

Modal:
Header: We are sorry
Text: There was a problem with the email address you provided:
<email address provided>
Bold Text: Please verify your email and try again.

If this problem persists, contact <contact email>

Button: "Try Again" & "Return to Engagement"

Scenario 4:
Matches wireframes:

https://xd.adobe.com/view/c19819d0-bedb-4427-93c3-d06f784fc2af-94cb/screen/a1efade1-d448-48da-ab15-3974b36c2dd3/specs/
https://xd.adobe.com/view/c19819d0-bedb-4427-93c3-d06f784fc2af-94cb/screen/342e6adc-7b0d-4feb-a271-cec3d2aed777/specs/
https://xd.adobe.com/view/c19819d0-bedb-4427-93c3-d06f784fc2af-94cb/screen/fb21a8fe-7f6e-4de8-b05e-e3e3db88569b/specs/

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/17?planning-poker) with ZenHub @tiagograf-AOT @saravanpa-aot @djnunez-aot @jadmsaadaot
