### ISSUE TITLE
Assigning a role (+Reviewer/QA) to MET/an engagement - User Management page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1703]
MA note:
We need to add the Viewer role to the modal.

----------------------------------------

As a MET system user, I want to assign roles to new users and add them to an engagement from the UM page.

+ Add User Button Text is removed and replaced by an "Action" column in the user table

New Reviewer requests access to MET by logging in
The action drop-down for new users will show:
Assign Role (Viewer, Reviewer, Team Member, Superuser) based on role permissions. If Reviewer/TM is selected, the modal will have the drop-down to add to an engagement (same as the current modal)

The user Details page won't be accessible until a role has been assigned to the user.

For existing users that already have a TM/QA role assigned, the drop-down will show:
Assign to an Engagement

Assign role modal:

Header: Assign Role to (user name)
What role would you like to assign to this user?
Viewer
Reviewer
Team Member
Superuser (only shown to Superusers +)

Which engagement would you like to assign this user to? (only shown if Reviewer/TM selected & only showing engagements the TM is already assigned to if added by a TM)

![Screenshot 2023-06-12 at 9.30.54 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/bab0a17a-ce24-44e3-9023-8c3655e196e5)

Add to Engagement modal:
![Screenshot 2023-06-09 at 3.32.14 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/02661fef-4807-41f5-87bf-a2919108f54b)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1703?planning-poker) with Zenhub @saravanpa-aot @VineetBala-AOT @jadmsaadaot

**Comment by tiagograf-AOT** [comment]
Add check to not allow a user to have both team member/super user role and a reviewer role - Only one role is permitted.

**Comment by VineetBala-AOT** [comment]
We have a new ticket to track the viewer role as currently we do not have a viewer role in MET. We need to define the access for a viewer role. Created a new ticket to track it: https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1746
