### ISSUE TITLE
Fix Survey created although disclaimer was not checked

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1728]
![image](https://github.com/bcgov/met-public/assets/101662408/4d0e761d-d708-462a-a323-23e6a39d6706)

from the Create Engagement page, if you go to Add A Survey and it's already an existing survey you can bypass the disclaimer. Let's just make it so you always have to adhere to the disclaimer ticky box.

**Comment by VineetBala-AOT** [comment]
Verified
