### ISSUE TITLE
ENGAGEMENT LISTING - action drop down view survey causes error if survey is not added

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1735]
![image](https://github.com/bcgov/met-public/assets/101662408/a2acbdbb-c814-40b4-8015-86f6bee05b4d)
 Fix this for for engagement listing page RELATED TICKET --- #1767 fixes SURVEY page action dropdown

**Comment by VineetBala-AOT** [comment]
Verified, view survey action not available for engagements without a linked survey.
