### ISSUE TITLE
Survey Report Settings

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1740]
As a Engagement Specialist I want to be able to select each questions that I want to be displayed in the report and also be able to select if a report link (What we heard report) should be sent when the engagement is closed so that i have control over what analytics the participants see.

Acceptance Criteria:

- New Dropdown action in the survey listing page "Report Settings"
- New action should be visible to SuperUsers only.
- New Survey Report Settings page.
- Page should display all survey questions with a checkbox "Display question in the report"
- Page should have a setting "Send what we heard report when Engagement is Closed"
- When Cloning a Survey these settings must be cloned as-well.

Marie Anik to provide wireframes.

*** When editing a survey, make sure to remove settings for removed questions
*** Keep in consideration comment questions "free text" might also be hidden from the dashboard.

**Comment by carlygreenehill** [comment]
Just back-end changes for this ticket :)

**Comment by VineetBala-AOT** [comment]
Back end changes completed as part of this ticket:
- New column called generate dashboard added to survey table to handle Send report toggle
- New report setting table added to handle selecting questions for public report
- New end points to refresh the report setting table with any change happening on the form
- ETL changes required to pull the above changes to analytics DB.
- Logic added on analytics to exclude un-selected questions from public report
