### ISSUE TITLE
Assigning a role (+Viewer) to MET - User Management page

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1746]
As a MET system user, I want to assign a viewer role to new users from the UM page.

New Viewer requests access to MET by logging in
The action drop-down for new users will show:
Assign Role (Viewer, Reviewer, Team Member, Superuser) based on role permissions.

View all permissions in this [spreadsheet](https://bcgov.sharepoint.com/:x:/t/04610/EbN6-RHdb5pIqqJrtaNdqocB-dhFxd39Q8OxvrV8_wKraw?e=Oqk2Cl).

Acceptance Criteria:
Engagement Listing: 
- able to view scheduled/published, open and closed engagements
- able to view approved comments
- able to select "View Survey" and "View Report" from actions drop down
- should not have any edit access

Survey Listing: 
- able to view all ready/linked surveys
- able to view approved comments
- able to select "View Survey" and "View Report" from actions drop down
- should not have any edit access

No access to user management and feedback tool.

**Comment by carlygreenehill** [comment]
@VineetBala-AOT  off the top of your head, how much effort is this? <3
