### ISSUE TITLE
'Take me to the survey" Button width

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1749]
As a user clicking on the 'take me to the survey' button, I feel the user flow would be more accurate if the button widths matched the same width as the 'Sign up for updates from the EAO' bottom button. This was seen on tablet view.![Screenshot 2023-06-19 at 1.52.11 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/f89c35b6-c33c-4b56-a355-7fdb30ec540b)

**Comment by marieanik** [comment]
Sign up for updates will be updated. Button in survey block matches BC Gov standards.
