### ISSUE TITLE
Text overlap - Tablet view

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1750]
As a public user I'd like to be able to read descriptions of projects clearly. When titles are 3 or more lines the paragraph  interferes with the date at the bottom. This seems to happen in tablet view 1024x1366

![Screenshot 2023-06-19 at 3.02.54 PM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/034a6b28-3915-41ec-b99f-8f5fa4822b85)

**Comment by VineetBala-AOT** [comment]
Verified.
