### ISSUE TITLE
Make entire card clickable (with a hover state)

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1766]
As a public user I want to know my options on the MET homepage.
So when I hover over Engagement card on the homepage I see each engagement box is clickable by it's hover tone #F2F2F2. - 50% opacity same destination as the 'Share your thoughts' button

![Screenshot 2023-07-13 at 11.49.19 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/d27d3351-104b-45e2-90fa-81aef71ff14f)

**Comment by VineetBala-AOT** [comment]
Verified.
