### ISSUE TITLE
Preview mode: different status view are not reflecting the public view

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1786]
This card has to do with the PREVIEW ENGAGEMENT feature for the backend user.

On the public site, depending on the status of the engagement you see:

Upcoming:
Header: no button
Survey block: button greyed out

Open:
Both buttons show and are active

Closed:
Header: no button
Survey block: button greyed out

On the preview, when you toggle the status:

Upcoming:
Header: Active button (should not show button)
Survey block: Active button (should show disabled button)

Open:
Both buttons show and are active (ok)

Closed:
Header: Active button (should not show button)
Survey block: button greyed out (ok)

**Comment by VineetBala-AOT** [comment]
Verified.
