### ISSUE TITLE
Update the engagement links sent in emails to use the slug (the custom vanity url path)

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1791]
Link sent in rejected email needs to be updated to new slug URL
Link sent in subscription email needs to be updated to new slug URL
Link for the survey result on submission email needs to be updated

**Comment by jadmsaadaot** [comment]
I think we are skipping the subscription and engagement edit and survey paths for vanity urls

**Comment by VineetBala-AOT** [comment]
Verified, link for the survey result updated to new slug url.
