### ISSUE TITLE
Overlapping elements - Tablet view - Public Side

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1819]
As a super user/team member it would be easier to understand engagement stats if elements weren't overlapping box's borders. Below is an image reference using a Google nest hub device 1024x600

![Screenshot 2023-07-10 at 11.05.35 AM.png](https://images.zenhubusercontent.com/63c595f1d8ede2145e2c4ad4/c4617e7a-3a2a-4561-ac80-f3dda6547379)

**Comment by carlygreenehill** [comment]
it does look funny when logged in to back end, but from public side of the report dashboard, tis good enough!
