### ISSUE TITLE
New Access Survey email content

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1832]
Email verification (sent to the person who wants to access the survey) (Same email sent if report id sent or not)

Change the text for:

Share your feedback about (engagement name).

Please click the link below to provide your feedback. This link will expire in 24 hours and is only valid once. If the link has expired, you can request access again at (public link to engagement).

Click here to `provide your feedback`.

Thank you,

The Environmental Assessment Office Team (will change for each instance)

---

This card helps us in #1773 because then we don't send an Engagement Closing Email when there is no auto report sent

**Comment by VineetBala-AOT** [comment]
Latest text is updated in the ticket 1919.
