### ISSUE TITLE
Update Question Type names in the form builder

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1876]
Survey = Likert
Select = Drop-down

And edit the text on the submit button to "Submit" (instead of Submit Survey)

**Comment by VineetBala-AOT** [comment]
Shows as below in dev:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0pUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--076ffa16f89c0a49925d49fb600a2a32ad545b51/image.png)


Submit button shows as "Submit Form" for multi page surveys, but as "Submit" on single page survey.

**Comment by VineetBala-AOT** [comment]
Verified, created a separate bug ticket to handle the text change for multi page survey submit button. 
https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/2113
