### ISSUE TITLE
Hard-coded text updates 2 -Widget selection

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1878]
To ensure all the cards display properly, change the font-size to bold, 16px for the name of the widget, and 13px for the description.

Add min-height so all the cards are the same height on smaller screens.

![Screenshot 2023-07-21 at 3.00.15 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/ad19b9bb-5730-4914-9496-52d3b1200ce2)![Screenshot 2023-07-21 at 2.53.35 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/7da6244d-2e0f-45c0-9609-d812ef5fd260)

Who is Listening
Add contacts to this engagement

Documents
Add documents and folders 

Environmental Assessment Process
Add the environmental assessment process info to this engagement

Sign Up for Updates
Offer members of the public to sign up for updates

Events
Add information about in-person or virtual information sessions

Map
Add a map with the project location 

***Fixing survey disclaimer typo** - "even if they do not collect personally information" should say "even if they do not collect **personal** information"

**Comment by carlygreenehill** [comment]
@jadmsaadaot / @djnunez-aot  best estimate, what's the effort in this card?

**Comment by jadmsaadaot** [comment]
not much effort, 1 as estimate

**Comment by VineetBala-AOT** [comment]
Verified.
