### ISSUE TITLE
Engagement Settings  - Save button & tweaks

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1885]
We will move the URL (links) to its own tab.

Only one "Save" button for the tab, at the bottom, separated from the Send Report section but a line.
Send Report is "on" by default
Send Report Label should be bold (like "Set-up as internal Engagement")
Both lines under the section header should be 13px, #707070

![Engagement-settings.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/5a0e1199-a828-4670-95d1-47a8a98cc0cd)

**Comment by VineetBala-AOT** [comment]
- All Report Settings should be editable until the engagement is published. Currently it can be changed for open engagement as well
- Send Report description says "Toggle this option off if you do not want an email with a link to the report to be automatically at the end of the engagement period." . I think it should be "Toggle this option off if you do not want an email with a link to the report to be automatically **sent** at the end of the engagement period."
- Send Report Toggle is should be automatically set to Send Report (default should be on) but the setting is by default off

**Comment by VineetBala-AOT** [comment]
Verified
