### ISSUE TITLE
localize the text in the app

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1894]
Have all the hard coded text in the app in one file in the app like this https://images.zenhubusercontent.com/61670716af0598935f770d72/0216e716-84c9-4fd5-b195-abf14a0bf2d1

This will allow us to have different texts for different tenants, different languages if needed and makes it easier to change texts in the app

ACCEPTANCE CRITERIA

- localize tenant-specific text
- when devs can pull text corresponding the tenant ex. header reads EAO vs. GDX 
- pulled dynamically dependent on tenant

**Comment by VineetBala-AOT** [comment]
Verified.
