### ISSUE TITLE
Team member can see upcoming engagements from the home page, but not when selecting "upcoming" on advanced search

### ISSUE THREAD

**Issue by TayaLee8** [bcgov/met-public#1904]
If there are upcoming engagements, they should be viewable from both the home page AND when "upcoming" is selected in advanced search.

Reported by Taya as a Team Member

**Comment by carlygreenehill** [comment]
@jadmsaadaot   --- can you ensure you fixed this?

**Comment by TayaLee8** [comment]
Passing in DEV
