### ISSUE TITLE
Survey Results whe no submissions have been made say "error to reload" - clicking does nothing

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1914]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHNIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3006c72f973b6c8a2676e896c9932aecb63c535c/Screenshot%202023-08-15%20at%201.01.01%20PM.png)
When viewing results for an open survey that does not yet have any submissions, the "Survey Results" section says "Error click to reload" - clicking does nothing.

**Comment by carlygreenehill** [comment]
Vineet fixed it, says Jad :)
