### ISSUE TITLE
Role on UM listing and User details should be Team Member (not member)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1917]

**Comment by VineetBala-AOT** [comment]
Verified and looking good in development, attaching screen shot:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXhEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4b4e990969a8e3af814b4f9f8fcfc3bfcf6aab4/image.png)

CC: @marieanik
