### ISSUE TITLE
Change text on collection notice - Subscribe email widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1925]

**Comment by TayaLee8** [comment]
**Final version:**

Personal information is collected under Section 26(c) of the Freedom of Information and Protection of Privacy Act, for the purpose of providing content updates and future opportunities to participate in engagements, as well as for the purpose of providing general feedback to evaluate engagements conducted by the Environmental Assessment Office.
If you have any questions about the collection, use and disclosure of your personal information, please contact the Director of Digital Services at Sid.Tobias@gov.bc.ca.

**Comment by djnunez-aot** [comment]
Completed for task https://github.com/bcgov/met-public/issues/1833 closing.
