### ISSUE TITLE
Feedback tool - PI warning

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1928]
As a member of the public, I want to see a warning on the feedback tool so that I am aware I shouldn't include any personal information.

Text: Please do not include any personal information in your feedback. Feedback that includes personal information will be deleted. 

A few minor tweaks: 
Remove the header
Move the X to close the modal a bit higher
Add the PI warning below the content
Remove the "Question" select box (underneath "What else would you like to share with us")

![Feedback-tool.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/a606b884-d520-4677-81f8-89f5d8aea5de)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1928?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
