### ISSUE TITLE
Feedback Tool - Mark as fixed/delete action drop-down

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1931]
As a Super User I want to have access to an action column added to the feedback tool so that I can archive it or delete feedback.

Acceptance criteria: Super Users can select an action from a dropdown menu to either delete feedback (hard delete) or archive it.

When the user selects delete feedback comment will be deleted permanently.

Superusers can click a button that says "View Archive" and can see the archived feedbacks.

When the user selects “Archive,” then "Archived” text will appear. Feedback can still be deleted.

Link to prototype:
https://xd.adobe.com/view/0102c78c-586a-4e00-8945-86d50f8a1af6-5451/screen/f96d7acf-296d-4cf5-b55c-7b6febe90d3d
 
 NOTE: please consider "Mark as resolved" instead as "Archive"

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1931?planning-poker) with Zenhub @aforde-aot @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by marieanik** [comment]
There was some slight change to this card that might confuse users. If the "Mark as Resolved" drop-down archive the feedback (and applies to ideas as well as issues, which cannot technically be "resolved") it would make more sense to change this option in the drop-down to "Archive".

@djnunez-aot will make that update.
