### ISSUE TITLE
Who's listening widget entry bug

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1942]
User enters contact info in the who's listening widget. 
Contact info is saved. 
User clicks create new contact and previous info from the contact entered is automatically entered.
Template should be blank.

Also, adding a contact with a photo, then adding a second contact without a photo automatically adds contact 1 photo to contact 2. Contact can't be deleted.

<img width="1792" alt="Screenshot 2023-08-01 at 11 27 07 AM" src="https://github.com/bcgov/met-public/assets/122822373/776070c4-44b9-4b97-b6c8-0432896df308">

**Comment by VineetBala-AOT** [comment]
Verified, working as intended
