### ISSUE TITLE
Hover state/ home page /Accessibility issue

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1945]
Current hover state (B) on home page engagements greys out text/buttons.
Please see attached image for reference. Should be link A (not B)
Xd demo: https://xd.adobe.com/view/3c3a99aa-4de1-42ec-ac36-ce2046fe7165-6969/
<img width="850" alt="Screenshot 2023-08-01 at 1 25 04 PM" src="https://github.com/bcgov/met-public/assets/122822373/012ba181-ad35-4aa0-ad07-49ce543213de">

**Comment by VineetBala-AOT** [comment]
Verified
