### ISSUE TITLE
Edits to the survey emails

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1948]
CURRENT NOTE: have to find the best way to change <email text> by tenant - refrence #2017 

**Change "Sender" from Modern Engagement Tool to PublicEngagementBC@notification.canada.ca** -- Carly Edit Sept 8: this is now part of bug ticket #2150

**The content of the email sent to access the survey needs to be edited slightly (move and edit the "Access will expire..." under the link AND change the text "public link to engagement to the actual link for that engagement, added in text as the example  "epic.engage.gov.bc.ca/engagement-name". Remove the last paragraph.)**

**UPDATE MA 29/08/2023** Share your feedback about (engagement name). NOT: Thank you for sharing your feedback about _engagement name_)

Please click the link below to provide your feedback.

`Provide Your feedback`

This link will expire in 24 hours and is only valid once. If the link has expired, you can request access again at `epic.engage.gov.bc.ca/engagement-name`

Thank you,

The Environment Assessment Office Team

From Carly: LOOKS GOOD! @marieanik did you want the subject line of this email to say "Survey for <name of engagement> ?  

@carlygreenehill Sorry, I should have added it here. Let's go for _engagement name_ - Access Link
***

**When a user submits the survey (and "Send Report" is on), they will now get an email:**

From Carly Sept 8: **@djnunez-aot**  this looks great -- can you please add a paragraph break between "Thank you for submitting your feedback" and "Written comments..." adjusted in the next below. 

Title: Your feedback was successfully submitted.

Thank you for submitting your feedback. 

Written comments will be reviewed and published within 7 days. Comments that contain personal information will not be published, and you may be contacted to amend your response. You can view written public feedback that has been submitted and reviewed thus far by clicking the link below.

 `Access Public Feedback`

Some feedback may be withheld until the end of the public comment period to ensure the integrity of the responses. All feedback relevant to the assessment of the project will be available at the end of the public comment period. You will receive an email inviting you to view the full results around _time_ on _engagement end date_.

Thank you,

The Environmental Assessment Office Team

***

**Email sent at the end of the engagement period (when "Send Report" is on)**

From Taya Sept 13th: This looks good except the text needs to still be changed to **Environmental** (currently says Environment) 

Title: The public commenting period for _engagement name_ is now closed. 

The public commenting period for _engagement name_ is now closed.

You can access the results by clicking on the link below. 

`View Feedback`

Thank you,

The Environmental Assessment Office Team

NOTE: Some work needed by #1825 to be able to change the SENDER in the EPIC.engage codecase

**Comment by djnunez-aot** [comment]
Had a discussion with devs. It seems updating the sender will not be possible for this task.
