### ISSUE TITLE
Internal user gets the 404

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#1959]
Internal user gets the 404 page after going into a survey and hitting the return to link.
![Screenshot 2023-08-02 at 2 54 57 PM](https://github.com/bcgov/met-public/assets/122822373/fc84ee30-441b-4a20-b6af-80abd8a0729e)

Solution: Devs, please remove the link.

**Comment by saravanpa-aot** [comment]
Discussed the solution options with @marieanik and decided to remove the link

**Comment by saravanpa-aot** [comment]
Good Find @Ian-UX-AOT
