### ISSUE TITLE
Preview Triggers a patch call on engagements

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#1962]
https://met-web-test.apps.gold.devops.gov.bc.ca/eao/engagements/173/view

clicking preview of this engagement brings up Error Updating engagement ..

<img width="1587" alt="image" src="https://github.com/bcgov/met-public/assets/39633456/c79c62e0-f758-4e7c-9cd9-497181727900">

**Comment by VineetBala-AOT** [comment]
Verified.
