### ISSUE TITLE
Landing page filter set to Open status still returns Closed engagements

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#1965]
@carlygreenehill MA note: tested today (sept. 15) on EPIC.engage dev and couldn't reproduce. The engagement closing today was showing as open. We can close this one.

To possibly recreate:

1. Have an engagement that closes on a date
2. Search for Open engagements on that closing date
3. See if the near-Closed engagement show ups with closed tag.

![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/e5cbf9b7-aaa7-4eb1-baaf-2d82392b3839)

**Comment by carlygreenehill** [comment]
@djnunez-aot  can you see if you can recreate this bug ticket

**Comment by carlygreenehill** [comment]
@marieanik + @TayaLee8 --- can you see if this happens, we use two engagements closing tomorrow (sept 14)
