### ISSUE TITLE
Capitalize the first letter of each word on "Share your thoughts" button (landing page)

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#1972]
Upcoming engagement shows "Share your thoughts" on landing page but once you click on it the engagement does not have the button. 

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/7a94a6dd-39da-4cbe-9298-c1424ff9fd08)

Upcoming engagement should have "View Engagement" instead??

**Comment by marieanik** [comment]
Yes, should be "View Engagement"

**Comment by VineetBala-AOT** [comment]
Verified
