### ISSUE TITLE
Header on the homepage is cut on mobile

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#2015]
Fix bug by setting a smaller size of the header "Environmental Assessment Office Public Engagement" 

Adjust size for engagement pages too, ensuring nice wrapping

![IMG_8888.PNG](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/252c78aa-4aa5-476f-8434-cb6bc683604a)

I'll check with Josh if we can make it shorter, or may reduce the font-size on mobile

**Comment by carlygreenehill** [comment]
We've created #2190 to fix this :)
