### ISSUE TITLE
User Management - Name Search not working

### ISSUE THREAD

**Issue by Ian-UX-AOT** [bcgov/met-public#2021]
1. When the user searches for a name in the User management search, no results are showing.

2. Search bar must have a capital “N” in “name”
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmtIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee8b2e85247126b6a00debaaa103295fa64b06e7/Screenshot%202023-08-15%20at%201.40.46%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad44aad611205120c0dc9902b31992a919c25839/Screenshot%202023-08-15%20at%201.40.55%20PM.png)

**Comment by VineetBala-AOT** [comment]
Verified.
