### ISSUE TITLE
Edit the flow and content of automatic updates

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#2031]
We will now send an automatic email when they subscribe (only content change for this one), when an engagement opens (not published), and at 9am PT, two days before the engagement closes (so if the engagement closes on Sept. 30, we will send the email at 9am on the 28th)

Acceptance Criteria:

1. cronjob
2. some text changes (see below)
3. cron has to observe the time of engagement, check at 9 am, and match to auto trigger email
4. will need testing to ensure that the '48hr before closing' email works appropriately

- Existing one (minor change)

**Confirm your subscription**
 
Title: Confirm your subscription
 
Thank you for signing up to receive updates for [Project name].

To receive updates, you must confirm your subscription by clicking the link below: 

Confirm Subscription

If you have received this in error you may ignore this email. 

Thank you,

The Environment Assessment Office
 
--------- 

New rules:

- **When an engagement opens**

 
Title: Share your feedback
 
A new engagement is now open for [project name]. 
 
To learn more and provide your feedback during this public comment period, please click the link below:
 
Provide Your Feedback

The public comment period ends on [Engagement closing date].
 
Thank you,
 
The Environmental Assessment Office
 
If you would no longer like to receive updates about this project, you may `unsubscribe`. (*smaller text)
 
 

- **At 9am, two days before engagement closes**

 
Title: Public comment period closes in 2 days
 
The public comment period for [project name] will close on [engagement end date] at midnight, Pacific time.
 
If you would like to provide your feedback, please do so before the date noted above.
 
If you have already provided feedback, thank you! You may ignore this email.
 
Provide Your Feedback
 
Thank you,
 
The Environment Assessment Office
 
If you would no longer like to receive updates about this project, you may `unsubscribe`. (*smaller text)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/2031?planning-poker) with Zenhub @VineetBala-AOT @djnunez-aot @jadmsaadaot @saravanpa-aot
