### ISSUE TITLE
Draft engagement shouldn't show in the list of upcoming engagement (home page)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#2064]
Only engagements that are scheduled or published (but not open yet) should show in the upcoming section.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e345adebb0d79a05b2c1fc8de54adf43b6bdb79c/Screenshot%202023-08-23%20at%2011.21.52%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjh3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c6762953170f68683ba7450837e6f18168b7554/Screenshot%202023-08-23%20at%2011.21.40%20AM.png)

**Comment by marieanik** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e345adebb0d79a05b2c1fc8de54adf43b6bdb79c/Screenshot%202023-08-23%20at%2011.21.52%20AM.png)

**Comment by carlygreenehill** [comment]
VINEET DID IT - fixed as part of another ticket, handled in PR #2012
