### ISSUE TITLE
Survey Results graph shows error when there are no results

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#2081]
1. Login as any role
2. Go to home page
3. expand an open engagement
4. Check the last graph

**Comment by djnunez-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUZiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ad6b8ddbec9ca28c41732c6324770b25a2eea389/image.png)
looking good
