### ISSUE TITLE
Change text on multi page survey submit button

### ISSUE THREAD

**Issue by VineetBala-AOT** [bcgov/met-public#2113]
For multi page survey the submit button shows text as "Submit Form", it should be "Submit" instead to be same as on single page surveys

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakpiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0e567b83eb046e637d6f578827c5db3d8b7f7c10/image.png)

**Comment by jadmsaadaot** [comment]
This has been discussed in formiojs repo: https://github.com/formio/formio.js/issues/2442

The solution that is available is to hide the default buttons and add custom ones
