### ISSUE TITLE
Generic 'Sender' for GC Notify

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#2150]
**As a** public viewer, I want to see emails from a generic but sensible email aka "Public Engagement"  [PublicEngagementBC@notification.canada.ca] so that I know this invitation to do the survey is legit.

## **Acceptance Criteria**

Change "Sender" from Modern Engagement Tool to [PublicEngagementBC@notification.canada.ca](mailto:PublicEngagementBC@notification.canada.ca)

Taken from ticket #1948. As of Friday, Sept 8, we are still getting the email from "Modern Engagement Tool <modernengagement@notification.canada.ca>"

@saravanpa-aot  - are we able to change this? MA is wondering if there is another thing we have to change in GC Notify 

<img width="743" alt="MicrosoftTeams-image (3)" src="https://github.com/bcgov/met-public/assets/101662408/4596b7a8-ee59-4a17-8a77-1d3d8048c879">
<img width="1079" alt="MicrosoftTeams-image (4)" src="https://github.com/bcgov/met-public/assets/101662408/769171dc-13db-4189-af54-ecebe367a37e">

**Comment by saravanpa-aot** [comment]
I change it and it looks like this
<img width="927" alt="image" src="https://github.com/bcgov/met-public/assets/39633456/25efd196-01b5-4156-8b06-0e5da7c60983">
