### ISSUE TITLE
Internal users logging in from an engagement page get a 404

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#2165]
Any time a user logs in (from any external page), they should see the MET "logged in" home page instead of a 404. 

User clicks the Admin Login link in the footer on any page > logs in > sees the home page

**How to recreate the bug:**

Go to an engagement page > scroll to Admin log-in > you get logged in but hit a 404 under 'Home'

**Comment by VineetBala-AOT** [comment]
Verified, it redirects to the home page.
