### ISSUE TITLE
support engage.eao.gov.bc.ca without context path eao

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#2180]
For EAO Land, 

1. The url should support https://engage.eao.gov.bc.ca/ instead of https://engage.eao.gov.bc.ca/eao.
2. any url should be working without eao in the url

https://engage.eao.gov.bc.ca/slug_url -> should direct to the engagement.

For GDX Land ,

1) the url need to have tenant name like GDX/EMLI 
   probably we can support a redirect here   https://mysurvey.gov.bc.ca/ can redirect https://mysurvey.gov.bc.ca/gdx 

Mostly we are looking at an environment variable which will decide the behaviour

**Comment by VineetBala-AOT** [comment]
Verified, eao urls work without the tenant name. URLs with slug directs to the engagement for public users and on user login directs to the home page.
