### ISSUE TITLE
Update formio library to have the new logic for conditionals

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#2186]
From https://github.com/formio/formio.js/issues/5144
"This is one of our Enterprise Features and is not part of this OSS library."

i.e. can't be done

**Comment by jadmsaadaot** [comment]
@carlygreenehill @marieanik

**Comment by saravanpa-aot** [comment]
We can probably find a way to get something which is close to this behaviour..
probably we could look at the ask from Josh once again (ask as in what exactly he needs it in the survey ) and help him to build the same thing using the advanced version (probably a dev can help here) ...

**Comment by carlygreenehill** [comment]
Can't upgrade to paid, making a work around using javasript
