### ISSUE TITLE
Deploy Highly Available DB

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#224]
We need to deploy an instance of Patroni instead of a single instance of the postgresql database.

Patroni is a HA (Highly Available) database architecture that prevent downtimes in case of a database crash.

Research & Implement task

**Comment by tiagograf-AOT** [comment]
We might need to consider the options (CrunchyDB, Patroni, EDB)

**Comment by carlygreenehill** [comment]
Ask community if they like CrunchyDB in Rocketchat
