### ISSUE TITLE
As an Admin, I want to add a widget to display important documents on the Engagement.

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#25]
**As an** Admin

**I want** to add a widget to display important documents to an Engagement

**so that** I can create folders and add documents to show on the Engagement.

### Scenario 1: 
Admin clicks the "Add Widget" in the Widget section.
Admin selects the "Document" card from the widget cards on the widget selection panel. 
Admin sees the "Document" panel. 
Section Header: Documents (+ edit icon = widget name is editable)
Checkbox to "Hide Title" (to hide title on published card)
"Create Folder" and "Add Document" buttons
"Save & Close" and "Cancel" buttons

### Scenario 2:
Admin clicks "Save & Close" to save the widget. Widget is created (even if no Document has been added).

### Scenario 3:
Admin clicks "Cancel" to exit. Widget is not created.

### Scenario 4:
Confirm user interface to the visual design
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/cca8437e-bd10-4dc8-b325-d8e824b6ea33,
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/b7897f6a-60ec-43c2-9bd0-4b089861032f

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)
![image.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/fc1b43db-98e4-4cc0-8aa9-02b051a47bbf)

**Comment by marieanik** [comment]
This will be one of the "widgets". Should we create a user story to add the widgets, then a task for each widget to be added? 
Who’s Listening?
Documents
Important links
Open House
Virtual Sessions

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/25?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
