### ISSUE TITLE
Public Landing Page

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#250]
As a BC Citizen I would like to have information about MET on its home page so that I can see and access all engagements.

Landing page will have a "MET" header (content tbd)
Content section:
Header
Search (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1243)
Cards for all engagements (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1237)
Pagination

Cards will show in order of Engagement dates.

Matches wireframe: https://xd.adobe.com/view/c19819d0-bedb-4427-93c3-d06f784fc2af-94cb/screen/4370b7c9-b62d-40df-bf17-b9c53a46017d/

**Comment by marieanik** [comment]
@tiago-aot There is no need for this. The "home" page will be EPIC.

@carlygreenehill @sidtobias Can you confirm this?

**Comment by sidtobias** [comment]
Or it will be the project page.  Or it might be a new page on EPIC let’s discuss


Sid Tobias

Director, Digital Services

Environmental Assessment Office

Government of British Columbia

Mobile:  (250) 893-6218

[signature_536649950]Twitter.com/BC_EAO<http://twitter.com/BC_EAO>



[Image]

________________________________

**Comment by marieanik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/250?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by carlygreenehill** [comment]
@tiagograf-AOT  --- i think we did this, right? ;)
