### ISSUE TITLE
Match made styles to "Flow 1" XD Colours/Fonts so that gov branding is on point

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#271]
See fonts/padding/colours etc. here on slide 1: https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/specs/

Full specs, fonts, and CSS available:

https://developer.gov.bc.ca/Design-System/Typography
https://developer.gov.bc.ca/Design-System/Primary-Button
https://developer.gov.bc.ca/Design-System/Secondary-Button

**Comment by tiagograf-AOT** [comment]
That’s a good start thanks @carlygreenehill

**Comment by jadmsaadaot** [comment]
Please try to update the fonts of the form builder in the same effort.
