### ISSUE TITLE
As an admin user, I'd like to use 'breadcrumbs' in order to see where I am in "edit/save/preview" engagement

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#272]

**Comment by jadmsaadaot** [comment]
https://mui.com/material-ui/react-breadcrumbs/

**Comment by marieanik** [comment]
@carlygreenehill Can we discuss this one? I think breadcrumbs can be useful but in this case Edit and Save is the same page (saved is just a state). When you go to the Preview Engagement, there is a huge banner and header (Preview Engagement) AND an Edit Engagement button. I'm concerned that this just creates bloat and confusion. Maybe we should test before implementing??

![Screen Shot 2022-07-06 at 12.27.26 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/5a98a585-bced-4a68-ac9a-94c0fa67b02e)

**Comment by carlygreenehill** [comment]
closing because we went in a different direction :)
