### ISSUE TITLE
MET ETL - Extract Transform and Load to Analytics DB

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#275]
As a follow up to https://github.com/bcgov/met-public/issues/274 ,

this story is about handling the extraction from MET and Loading in to Analytics DB.We wiill be using python scripts for doing it in the interest of MVP.

the key item will be JSON survey data transformation to Analytics db structure

Post MVP , if it suits , we will look at other opensource ETL tools as apache airflow or Dagster or nifi

**Comment by tiagograf-AOT** [comment]
- [ ] Cron job to read submission json and transform it into a flat table
