### ISSUE TITLE
Add Fider for MET 

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#29]

**Comment by sidtobias** [comment]
https://fider.io/

**Comment by tiagograf-AOT** [comment]
@sidtobias saravan had previously sent us this link a fider link to us, I believe it was deployed in one of EAO openshift namespaces.

https://met-fider.apps.silver.devops.gov.bc.ca/

**Comment by tiagograf-AOT** [comment]
@sidtobias I have deployed a fider instance in our openshift namespaces, this is the url:

https://met-fider.apps.gold.devops.gov.bc.ca/

I may have to talk to Steve or Saravan to take down the instance that is running on eagle.

**Comment by tiagograf-AOT** [comment]
@sidtobias we might want to change its route since they are pretty similar "met-fider.apps.silver" vs " met-fider.apps.gold" 

I just gave you admin access!
