### ISSUE TITLE
Side menu doesn't reflect URL

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#292]

**Comment by tiagograf-AOT** [comment]
When navingating to a url directly the side menu does not highlight the right menu item.

![Screen Shot 2022-07-07 at 10.47.14 AM.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/a2a827b7-6073-499f-8d2c-7c39715b1c4a)

Actual
navigate to http://met .../survey
Engagements in the side menu is highlighted

Expected

navigate to http://met .../survey
Survey in the side menu is highlighted

**Comment by saravanpa-aot** [comment]
@tiagograf-AOT plz verify it
