### ISSUE TITLE
Close an engagement

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#294]
When the engagement end date is due, update engagement status  to closed.
Show status Closed when viewing the engagement.
Survey submissions are not allowed when the engagement is closed.

**Comment by tiagograf-AOT** [comment]
- [ ] Cron job to check engagement dates
- [ ] Update engagement view to show status (as per design)
- [ ] Update submissions to check engagement status
- [ ] Update survey to not be displayed when engagement is closed

**Comment by sidtobias** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/294?planning-poker) with ZenHub @saravanpa-aot

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/294?planning-poker) with ZenHub @djnunez-aot @jadmsaadaot @tiagograf-AOT
