### ISSUE TITLE
 solution - email sending

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#309]
Evaluate 

1) CHEF Email service
https://digital.gov.bc.ca/common-components/common-hosted-email-service

2) Direct integration with GC Notify. ( comes with the benefit of text messages )
https://notification.canada.ca/features

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/309?planning-poker) with ZenHub @djnunez-aot @jadmsaadaot @tiagograf-AOT @saravanpa-aot
