### ISSUE TITLE
Validate email through CAPTCHA

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#334]
When signing up for a survey a user can enter an email multiple times and register without any bot or limit control, meaning that a malicious person could be spamming emails with our MET system survey/subscription email.

We need to research ways/tools to prevent this.

**Comment by tiagograf-AOT** [comment]
possible solution:

https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html

**Comment by tiagograf-AOT** [comment]
Flask-Limiter might be a good option for limiting access to one specific endpoint.  
https://flask-limiter.readthedocs.io/en/stable/index.html

While the route configuration on openshift would be a API wide configuration more about a full on site attack.
https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html

Other solutions include having honeypot and time-based forms patterns. Multiple examples can be found online and those won't prevent hits to the API directly.

All solutions are not fool proof and just target reducing the vulnerability.
