### ISSUE TITLE
Rate this App - Feedback Tool

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#337]
Tool - Closed: https://xd.adobe.com/view/e4c46788-b31b-43a0-a4dd-ae2cc2439b58-b197/screen/370dce46-bffc-486a-be89-b4bd4579bf97/
Tool - Open: https://xd.adobe.com/view/e4c46788-b31b-43a0-a4dd-ae2cc2439b58-b197/screen/a1eb2f43-8e81-47a1-b8ef-725484469c21/
Tool - filled: https://xd.adobe.com/view/e4c46788-b31b-43a0-a4dd-ae2cc2439b58-b197/screen/cc6df54a-5bfd-4f2c-9886-c8b35bbfd385/
Tool - Submitted: https://xd.adobe.com/view/e4c46788-b31b-43a0-a4dd-ae2cc2439b58-b197/screen/73eddca0-408c-4d09-b2e1-e04c41978b5c/
Tool - Admin: https://xd.adobe.com/view/e4c46788-b31b-43a0-a4dd-ae2cc2439b58-b197/screen/c50b5e94-c060-44d5-a636-4be6c3004e64/

*I'll email you the SVG files

*OLD comment: I found these two open source tools:
https://madewithsvelte.com/bromb 
https://www.rowy.io/blog/feedback-fin
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/9212e88b-68d2-4964-a6ea-89bd23872a9f)

**Comment by jadmsaadaot** [comment]
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/ca42c91d-d898-4430-8b29-1b0d7e82be58)
