### ISSUE TITLE
Redash Customisations 

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#342]
Redash visualisations has to be customised so that UX/UI patterns are aligned with MET.

1) Font changes to align with MET .

2) Hiding Filter choice for survey id/engagement Id so that user wont be presented with the filter .

CI/CD approach also has to be evaluated in this task since custom image has to be built on top of redash base image and also the custom code has to be stored in github.

**Comment by VineetBala-AOT** [comment]
Added the bc fonts on to the below files:
client/app/pages/dashboards/DashboardPage.less
client/app/pages/dashboards/PublicDashboardPage.less

Page header and Footer removed on the public dashboard by editing the below file:
client/app/pages/dashboards/PublicDashboardPage.jsx
