### ISSUE TITLE
Tweaks to Engagement header

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#351]
Header should be H1 (2.3rem)
Make the "Status" label and text in badge bold

MA note: Engagement dates are now 1.9rem (should be 16px bold). Must be a header tag still on there. 
Also, badge text should be bold.

The rest is all good.

 ![Screen Shot 2022-09-08 at 12.33.48 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/6d6795ee-620f-4c20-b3b0-6ebfff4de478)

**Comment by jadmsaadaot** [comment]
In any page that we want to be friendly to all screen sizes we shouldn't use px for spacing and margins. We would need a dynamic unit like em

**Comment by marieanik** [comment]
@jadmsaadaot for the margin below the header, feel free to add it in em. I'm just not sure what the value should be. I attached a picture so as long as there is a bit more spacing between the header and description like on the mockup, I'll be happy.![Screen Shot 2022-08-10 at 10.55.26 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/1a1b9914-0e0c-4753-8e54-35a35a7c1033)

**Comment by marieanik** [comment]
@jadmsaadaot I just added my comments. Please review.
