### ISSUE TITLE
As an admin, I want to remove a survey from a draft engagement

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#358]
Admin adds a survey to engagement, can remove it by clicking the "remove" icon on the survey tile.

Modal pops up.

Content:
Header: Remove Survey 
Content: You will be removing <survey name> from <engagement name>. This survey will not be deleted and will be available to add to an engagement, or directly from the Survey page. Do you want to remove this survey?

Buttons: "Cancel" & "Remove Survey"

https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/f2b3759e-bacb-41ae-ae84-e74c304877d8/

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/358?planning-poker) with ZenHub @saravanpa-aot @djnunez-aot @VineetBala-AOT

**Comment by carlygreenehill** [comment]
YOU COMPLETED THIS ONE? 😃

Carly Greene Hill (she/her)
Business Application Analyst
Environmental Assessment Office
Government of British Columbia
Mobile:   250-208-5380
