### ISSUE TITLE
Add "read more" to engagement description

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/met-public#361]
Previously: Add a read more for the engagement description

Let's give a max character limit of 550 characters to the description. Remove the margin of 16px on the description div and 16px padding-top to the engagement dates.

![Screen Shot 2022-12-20 at 6.07.57 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/8e9b0a7f-3357-4a08-8714-a77112fffe53)

**Comment by tiagograf-AOT** [comment]
possible limiting the max characters for the engagement description (not content)

**Comment by carlygreenehill** [comment]
Do need a wireframe for this? 

I assume it's just adding a little "+ read more" thingy, vice the scrollbar in Engagement Description
