### ISSUE TITLE
Survey link - verify email content

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#362]
Email title: <Engagement name> survey link - link expires in 24h

Email content: Thank you for your interest in sharing your thoughts about <Engagement name>.

Please click the link below to access the survey and share your comments. This link will expire in 24h **and is only valid once**. 

<Click here to share your thoughts>

You can view the survey results anytime on <our report page>. The comments will be available for viewing when the Engagement period is over, starting <engagement close date>. 

Thank you,

The EAO Team (?)

**Comment by marieanik** [comment]
@carlygreenehill I drafted this email for the email verification. Can you please have a look and tweak/add as needed?

**Comment by carlygreenehill** [comment]
It's wonderful! Just for now, let's remove the part about "You can view the survey results anytime on ." until we discuss a bit more about how we'll share tabulated data with the public.
