### ISSUE TITLE
Allow rollback when error occurs between database transactions

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#396]
If an error occur during multi step database statements the system should be able to rollback the changes previously made.

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/396?planning-poker) with Zenhub @tiagograf-AOT @saravanpa-aot @VineetBala-AOT
