### ISSUE TITLE
As an Admin, I want to preview all the statuses of an Engagement

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#398]
**MA UX Note:**

As discussed with Saravan, let's change the label for "Click to View Different Engagement status"
Make label 13px in size
Reduce padding between label and badges to 8px
Make border #cdcdcd

![Screenshot 2023-01-04 at 6.11.54 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/85ffc504-5646-4cad-9346-cbc8a63c22ed)

As an Admin, I want to preview all the statuses of an Engagement

*This is an update to the current preview screen

New box to display the different devices to preview the Engagement on the right. Label: "View on different devices:"

New box to preview the different statuses Label: "View Different Engagement Status:"
Upcoming, Open, and Closed badge (Will toggle between the different Survey block text)

https://xd.adobe.com/view/65ea110d-ea8c-496c-919b-10e890cdea9e-30b9/screen/f722494e-5c5c-48ac-8a03-819abe2e704d/

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/398?planning-poker) with Zenhub @carlygreenehill @djnunez-aot @jadmsaadaot @marieanik @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
Default status when previewing engagement should be the current engagement status
