### ISSUE TITLE
The only mandatory fields to create an engagement should be Engagement Name and Date

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#402]
As a Engagement Specialist I want to create an engagement only using its name and dates at first so that I can enter a description and content in the future.

Acceptance Criteria

Create/Update engagement only required fields are Name and Date
Preview Engagement banner shows missing description and/or content.

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/402?planning-poker) with Zenhub @carlygreenehill @djnunez-aot @jadmsaadaot @marieanik @saravanpa-aot @VineetBala-AOT

**Comment by marieanik** [comment]
@djnunez-aot Just tested in Dev andf still getting the "Content missing" error message.![Screen Shot 2022-12-16 at 7.28.22 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/e7c4c009-5421-4bb8-8734-271bf6386462)

**Comment by djnunez-aot** [comment]
@marieanik The pr is not merged yet so it is still only on my local I will ping you once it is ready for testing
