### ISSUE TITLE
Default Engagement text to BC Sans (font-size 16) when you cut and paste text. Add BC Sans to Font options.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#403]
If you cut and paste text, it keeps it's formatting, including the font and font-size. We can change the font size to 16 manually but it would be best to format it directly. Font BC Sans is not available from options so you can't change it to Bc Sans.

**Comment by jadmsaadaot** [comment]
Remove ability in rich text editors to have fonts changed from BC Sans
