### ISSUE TITLE
Date published doesn't always show up on Engagement listing

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#408]
I created and published the last two engagements. Both are published but the date for the first one doesn't show up.
Logged out, came back in MET and now the date doesn't show up for the second one as well.

![Screen Shot 2022-08-09 at 2.26.40 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/110d4839-9389-4aaa-add3-edb043cc12a8)
![Screen Shot 2022-08-09 at 3.31.22 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/41a9d25c-cf78-47c6-ab8b-4b10b15bc370)

**Comment by saravanpa-aot** [comment]
@marieanik can you verify this?
