### ISSUE TITLE
As an Admin, I want to be able to see the status of the engagement on the Engagement page (tweak) *click edit to see text

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#413]
The current status table shows Draft/Published (and Scheduled when implemented). We need to replace the status of Published with the status of the engagement as can be seen on the engagement page: Upcoming, Open, Closed. (These statuses indicate that the engagement has been published).

The possible options for this column will be:
Draft
Sent for Review (future implementation)
Scheduled (future implementation)
Published - Upcoming
Open
Closed
Archived (future implementation)

The Status column will appear after the "Date Published" column on both the Survey and Engagement pages.

https://xd.adobe.com/view/65ea110d-ea8c-496c-919b-10e890cdea9e-30b9/screen/49c929ce-c321-4ce2-9a12-7e75bc82b5d4/

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/413?planning-poker) with Zenhub @carlygreenehill @djnunez-aot @marieanik @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by marieanik** [comment]
Yes, please @VineetBala-AOT

**Comment by carlygreenehill** [comment]
@marieanik  --- i think this card is looking good! 

thoughts: in Engagements tab, the Status column comes between "date created" and "date published"  -- that's where you wanted Status to appear, yes? 

in Surveys tab, Status column appears farther right just before "Reporting". I find this view easier on the eyes for some reason!
