### ISSUE TITLE
update of an engagement should use Patch instead of PUT

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#510]
![putvspatch.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/b736539e-bf86-46ca-a4b1-2637e88a61cc)update of engagement as name , published date etc are handled in PUT where the whole resource is updated which is not ideal.
PATCH is recommended in this case and UI has to send only whats getting updated.

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/510?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
