### ISSUE TITLE
What We Heard report doesn't re-size correctly depending on screen

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#520]

**Comment by carlygreenehill** [comment]
![Capture](https://user-images.githubusercontent.com/101662408/186726738-a6c53784-cf6d-4090-a3d7-13eef2963d14.PNG)

**Comment by saravanpa-aot** [comment]
Solution options
1) Hide the toolbox in mobiles
2) Hide the text with in the chart since its already displayed as a legend
