### ISSUE TITLE
Update all MUI containers with direction='row' 

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/met-public#531]
for readability and future proof

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/531?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
