### ISSUE TITLE
Improve and arrive at consistent url patterns in UI

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#558]
Engagement related should ideally be 
engagement/:id/action

Survey should ideally be 
survey/:id/action

There should a default route as well /survey/:id should bring a page 

https://met-web-dev.apps.gold.devops.gov.bc.ca/survey/build/29 Should be changed to https://met-web-dev.apps.gold.devops.gov.bc.ca/survey/29/buildd

https://met-web-dev.apps.gold.devops.gov.bc.ca/engagement/form/59 Should be https://met-web-dev.apps.gold.devops.gov.bc.ca/engagement/59/form

@jadmsaadaot @tiago-aot feel free to add your thoughts here

**Comment by jadmsaadaot** [comment]
Also we need to consider action when there is no id, engagement/action, and survey/action.

For the listing pages engagement/listing or list, survey/listing

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/558?planning-poker) with Zenhub @VineetBala-AOT @tiagograf-AOT @djnunez-aot
