### ISSUE TITLE
As an Admin,  I want to save an Engagement as draft.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#56]
The user interface must follow the visual design as per https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/c50b5e94-c060-44d5-a636-4be6c3004e64 (Engagement saved as draft shows on table with status of "Draft") and https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/32caf4d5-99c5-4df2-9e43-620e6b838203

Admin User clicks "Save Engagement Draft" button at the bottom of the Create Engagement page.
Draft Engagement is saved.
Draft Engagement shows up on Landing page table with a status of "Draft".

**Comment by marieanik** [comment]
Admin User clicks button at the bottom of the Create Engagement page. 
Draft Engagement is saved.
Draft Engagement shows up on Landing page table with a status of "Draft".

**Comment by tiagograf-AOT** [comment]
@marieanik can we close this card? Today when we save an engagement its always saving as a draft already, and there's a bug we are fixing where the "Draft" status is not showing up in the engagement table.
