### ISSUE TITLE
As an admin, I want to have more options to search the engagements

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#572]
MA note: Labels need to be #494949 (not #00099) and let's make the checkboxes closer (half the space)

As an admin, I want to have more options to search the engagements.

##Scenario 1##
Advanced Search button is enabled on the Engagement listing page. The button has an arrow showing if the advanced search is open or closed. Admin clicks the button to open advanced search.
https://xd.adobe.com/view/65ea110d-ea8c-496c-919b-10e890cdea9e-30b9/screen/c50b5e94-c060-44d5-a636-4be6c3004e64/

##Scenario 2##
Advanced Search is opened. We see the following search fields:
**Label:** 
Status
Checkboxes:
Draft
Scheduled
Published
Open
Closed
**Label:**
Date Created - From
Input: date field
**Label:**
Date Created - To
Input: date field
**Checkbox:** Has comments that need review
**Label:**
Date Published - From
Input: date field
**Label:**
Date Published - To
Input: date field
**Label:**
Engagement Phase
Input: dropdown with engagement phases *Not developed yet
Buttons: "Reset All Filters" "Search"
https://xd.adobe.com/view/65ea110d-ea8c-496c-919b-10e890cdea9e-30b9/screen/49c929ce-c321-4ce2-9a12-7e75bc82b5d4/

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/572?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by jadmsaadaot** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/572?planning-poker) with Zenhub @saravanpa-aot
