### ISSUE TITLE
As an admin, I want to be able to have more options to search the surveys.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#573]
MA note:

Please add icons. :)

As an admin, I want to be able to have more options to search the surveys.

##Scenario 1##
Advanced Search button is enabled on the Survey listing page. The button has an arrow showing if the advanced search is open or closed. Admin clicks the button to open advanced search.

![Screenshot 2023-05-31 at 5.12.21 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/456b1c3b-bfd4-4a7d-afa0-c7008e10c8fb)##Scenario 2##
Advanced Search is opened. We see the following search fields:
**Label:** 
Status
Checkboxes:
(in the format Icon/text)
Template
Ready
Linked

**Label:**
Date Created - From
Input: date field
**Label:**
Date Created - To
Input: date field

**Label:**
Date Published - From
Input: date field
**Label:**
Date Published - To
Input: date field
**Label:**

Buttons: "Reset All Filters" "Search"

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/573?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
