### ISSUE TITLE
Achieve 80% of unit test coverage for Front End Components

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#587]

**Comment by djnunez-aot** [comment]
Cypress?

**Comment by djnunez-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/587?planning-poker) with Zenhub @tiagograf-AOT @jadmsaadaot @saravanpa-aot @VineetBala-AOT
