### ISSUE TITLE
Create front end unit test for Engagement Form

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#589]
Make sure 80% of EngagementForm component is covered by unit test so that we can use it as a template for other entities

**Comment by djnunez-aot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/589?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
