### ISSUE TITLE
Incorporate security threat analysis tools 

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#596]
- Sonar cloud
- Code Climate
- Code Cov
- OWASP ZAP

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/596?planning-poker) with Zenhub @saravanpa-aot @tiagograf-AOT @djnunez-aot @VineetBala-AOT

**Comment by carlygreenehill** [comment]
Scan to Notify API to finish
