### ISSUE TITLE
Admin Site - Landing Page - Side Navigation

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#65]
As an Admin I need a menu so that I can access the different pages of the application (survey, engagements, etc)

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/65?planning-poker) with ZenHub @djnunez-aot @jadmsaadaot @tiagograf-AOT

**Comment by marieanik** [comment]
https://xd.adobe.com/view/7360b654-4a25-4140-9670-a56f4adabe7a-2633/screen/c50b5e94-c060-44d5-a636-4be6c3004e64/

Active: #FFC107
Other link: #FFFFFF
Background: #003366
