### ISSUE TITLE
As a member of the public, I want to learn more about each phase of the engagement in the Engagement Phases widget (Desktop)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#670]
As a member of the public, I want to learn more about each phase of the engagement in the Engagement Phases widget (Desktop)

Acceptance Criteria:

Member of the public accesses an Engagement page with the engagement widget on it.

Matches wireframe:
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/b6e74f21-2177-475b-a224-42fbcbbeb0be

Title: The EA Process
Text:  Click on the sections below to expand them and learn more about each EA process phase. You can also learn more about each engagement period by clicking the engagement icon. 

Include the following text in the arrow above the graphic:
 Engagement and consensus-seeking with participating Indigenous nations occur at each stage of the process, supported by dispute resolution at certain stages if required.

Sections are clickable and each one opens a box with the description (static) of the phase.

Text as on PDF:
[https://app.zenhub.com/files/480383041/ddd4fc0f-35c3-4abf-9e27-3110a3579db7/download](https://app.zenhub.com/files/480383041/ddd4fc0f-35c3-4abf-9e27-3110a3579db7/download)

Matches wireframe:
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/778f3bf2-c219-4d57-bdab-0de013a839ec

Each Engagement icon is clickable, opens a box with the following text for each engagement:

Early Engagement: 

Tell us about your interests, issues and concerns about the initial proposal for the project. How would the project as proposed personally affect you, your family, or your community? Tell us how you want to provide feedback and be involved in the rest of the assessment process. 

Process Planning: 

Tell us what you think of the draft process order and assessment plan. Have we captured everything that should be assessed and the information required? Are the timelines and assessment methods appropriate? What do you think of how we plan to collect feedback from the public? 

Application Review: 

Tell us what you think about the proponent’s application. Are there effects that haven’t been fully considered? Now that you have the proponent’s full assessment, is there anything new or is still raising concerns for you? Do you think something has been assessed inaccurately? 

Effects assessment and recommendation:	 

Tell us what you think about the package of draft decision materials that will be provided to Ministers, who will decide whether or not to issue an environmental assessment certificate. Is anything missing? Has something been assessed incorrectly? What should the ministers consider that isn’t already included? 

Matches wireframes:
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/a2eb4142-b5a9-4add-b0d3-c65a5139f1dc

**Comment by tiagograf-AOT** [comment]
@marieanik to provide the mockups

**Comment by tiagograf-AOT** [comment]
@saravanpa-aot

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/670?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
verified and closed, created a bug regarding. the "selected" phase
