### ISSUE TITLE
Subscribe to an engagement widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#680]
As a MET system user, I want to add a subscribe widget so the public can register to be on the EAO mailing list.

##scenario 1## 
MET system user clicks button to add widget, sees an option to add subscribe widget. 
Name: "Sign Up for Updates"
Description: "Offer members of the public to sign up for updates"
![Screen Shot 2022-12-19 at 10.58.00 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/396b5267-7080-4cd2-a0a0-9bc01cedbc2a)
Selects that option, and widget is automatically added to the widget section. (with a confirmation message)

##scenario 2##
Preview/public view 
Header: Sign Up for Updates
Content: If you are interested in getting updates on public engagements at the EAO, you can sign up below:
Button: Sign Up for Updates from the EAO
![Screen Shot 2022-12-19 at 10.56.37 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/2f0fdf24-9d48-4694-8445-2363b5698e63)
Opens Modal:
Header: Sign Up for Updates
Content: Sign up to receive news and updates on public engagements at the EAO.
FOIPPA and input field for email (same as validate email modal)
Buttons: Cancel & Submit
![Screen Shot 2022-12-19 at 11.01.32 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/ac653723-10a2-4722-8d88-6e9b37f2c83b)

#scenario 3## 
Public user fills in the modal and clicks Submit.

Receive a confirmation message in the modal.

Header: Thank you
Text: We sent a link to confirm your subscription at the following email address:

Bold Text: Please click the link provided to confirm your interest in receiving news and updates from the EAO.

Button: "Close"

![Screen Shot 2022-12-22 at 7.37.16 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/973249b5-e09d-4db7-930a-7eaecc2c2b58)

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/680?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
