### ISSUE TITLE
Admin Site - Landing Page - Basic Search

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#69]
As an Admin I want to be able to filter/search engagements by name so that I can easily find it in the list.

**Comment by marieanik** [comment]
@sidtobias Are we doing this for the prototype? Simple search? Advanced?

**Comment by sidtobias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/69?planning-poker) with ZenHub @djnunez-aot @jadmsaadaot @tiagograf-AOT
