### ISSUE TITLE
User details page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#715]
As a MET system user, I want to be able to see other users' detail pages so that I can see their roles and the project they worked on.

System user is on the user management page (listing) (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/714) and clicks on a user name.

https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/24e95953-0a12-4052-8818-9977fd6c0b79/specs/

NOTES
*#966 handles: The "Assign Superuser Role" toggle is only enabled if the user is a Superuser/Instance Admin.
*#1273 handles: the The "Deactivate User" toggle is only enabled if the user is Instance Admin.
*#720 handles: "Add to Engagement" button is disabled if user is a viewer

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/715?planning-poker) with Zenhub @tiagograf-AOT @jadmsaadaot @VineetBala-AOT
