### ISSUE TITLE
Add a TM to a engagement from the User details page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#720]
As a MET system user, I want to add a TM to an engagement from the User Details page.

##Scenario 1##
Admin clicks on the "Add to an Engagement" button on the User Details page. Modal opens.
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/e8eba04c-6967-4900-b192-c25d48ec7b4b/specs/

content:
Header: Add (User Name) to an Engagement
Dropdown: Which Engagement would you like to add (user name) to?
(All draft, upcoming, and open engagements listed if user is Superuser/Instance Admin. If User is TM, they can only see and select projects they are assigned to.)
Buttons: "Submit" and "Cancel"
https://xd.adobe.com/view/7d5f6547-2523-484d-8101-a7587f9076c8-280c/screen/e8eba04c-6967-4900-b192-c25d48ec7b4b/

Superuser/TM/Instance Admin clicks submit, sees confirmation/notification message: You have successfully added (user name) as a Team Member on engagement name.

Engagement gets added to the list of engagements the user is assigned to on user detail page.

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/720?planning-poker) with Zenhub @jadmsaadaot @tiagograf-AOT @VineetBala-AOT
