### ISSUE TITLE
Make list of what we need to go LIVE into PROD

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#730]
~~HA database~~
~~Openshift Prod deployment~~
~~Sysdig~~

Development
- Finish analytics data (remove mock/fake data, finish implementing location with Snowplow)
- Zap scan check pass (address issues raised by zap scan)
**- recaptcha or some way to prevent spamming when sending emails.**
- Load/Performance test (optional)

Documentation

- PIA / STRA approvals
- URL / SSL - chosen + approved!

**Comment by tiagograf-AOT** [comment]
moved into EPIC
