### ISSUE TITLE
Research form.io / react capabilities for new survey questions

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#734]
Research for the following cards to come on...

- VC style question...
   - needs list of checkboxes, select boxes?
   - pull data from other component in form.io
   - customize 'checkboxes' to fit design in form.io 
   - create labels

- pagination - DUH, WE CAN 
-Likert is already available in form.io as "Survey"

 This card is probably for the Jad 😉

**Comment by carlygreenehill** [comment]
Timebox - estimated time = 5

**Comment by jadmsaadaot** [comment]
@carlygreenehill  @marieanik pagination with a progress bar is already doable. We know that already so for that you don't have to wait for an answer, it's yes.

**Comment by jadmsaadaot** [comment]
- Check boxes can be dynamically populated by adding a hidden component and adding Javascript logic under Custom Default Value in the Data tab to use Formio.fetch and pull the VCs and then pull the checkbox component by using a utility function and then populating its values field manually.
- Checkbox layout could be altered by pulling the checkbox component as is from the Formio repo then making changes to the template.ejs
- Tags component could be created by extended custom html element and adding a template for it. It can be populated by adding a a custom logic to it in the Logic tab that triggers on change of checkbox,  checks which checkboxes are true and appending values to the value field
