### ISSUE TITLE
As an MET system user, I want to see and approve/reject all the written comments made by one person on one page.

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#740]
As an MET system user, I want to see and approve/reject all the written comments made by one person on one page.

Scenario 1:
MET survey has more than one single or multiple line answer question. **On the comments review page, User sees all the comments, separated by a #f2f2f2 line**. Comments (all) can be approved or rejected. 

![Screen Shot 2022-11-08 at 1.16.59 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/231eba79-6ea0-4eb7-94d3-48cd10bc4b35)
https://xd.adobe.com/view/7d5f6547-2523-484d-8101-a7587f9076c8-280c/screen/8cc0f2d1-ba05-48fd-9b6e-ec7b321e8c47

Consideration: leave space for sentiment analysis and VC icons on the right of the comments. Reason for rejection will be added later.

![Screen Shot 2022-10-18 at 11.48.32 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/ae9b56ae-ae96-4f28-b67f-0ceae285d4a2)

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/740?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
