### ISSUE TITLE
Formio Custom Validation/Conditional disabled

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#757]
Formio formbuilder won't work with CSP 'unsafe-eval' disabled, this seems to be a known issue: https://github.com/formio/formio.js/issues/2849
I've currently disabled evals in fornio by setting: Formio.Utils.Evaluator.noeval = true;
but this will cause some of the features to not work (Custom Validation and Custom Conditions), We might need to investigate with other teams if there's a better solution

**Comment by carlygreenehill** [comment]
@jadmsaadaot + @TayaLee8  - hello it's been almost a year since we created this bug. can you please see if this card is still relevant? please reply with a comment on this thread as to what you find

**Comment by jadmsaadaot** [comment]
@carlygreenehill not relevant we have no custom validation or custom conditions needs and we do not expect admins to write code in formio code (which is what is needed to do custom conditions and custom validations). I will close it
