### ISSUE TITLE
Break down nginx conf by environment

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#778]
nginx configuration is global and should be broken down by each environment (dev, test, prod)

**Comment by saravanpa-aot** [comment]
@tiagograf-AOT we generally do wildcards in ngxin config like *.gov.bc.ca to avoid nginx config to be very specific and thus configure for each environment.. If thats the motivation for this ticket

**Comment by saravanpa-aot** [comment]
![image.png](https://images.zenhubusercontent.com/5e6295b447fbde831b854aa7/c56c75f5-f665-4915-a8c2-57f8e94c11fd)


![image.png](https://images.zenhubusercontent.com/5e6295b447fbde831b854aa7/f4b1a974-c192-4843-8719-f4c5200d704c)

CSP headers looks good for each environment.
