### ISSUE TITLE
As a public user, I'd like to see the Who is Listening Widget on Engagement Page

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#784]
As an Engagement specialist I want to be able to see the added who is listening widget in the engagement preview page so that i can confirm that the information is correct

this user story also applies to a public user:

As a BC Citizen I want to be able to see who is listening to an engagement so that I feel heard and more connected to issue/cause raised by the engagement.

**Comment by carlygreenehill** [comment]
See cards 142, 143, 144 for similar cards.

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/784?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT
