### ISSUE TITLE
SPIKE : Text similarity  using Machine Learning

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#834]
Explore the possibilities of doing text similarity using Machine Learning/NLP so that its helpful for staff to see the comments came from a form letter.

For example : 
https://huggingface.co/shafin/distilbert-similarity-b32

**Comment by VineetBala-AOT** [comment]
This can be implemented using ML models which can provide a percentage match between the texts. Threshold value of the percentage to determine a match needs to be decided. 

Sample models:
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2
https://huggingface.co/shafin/distilbert-similarity-b32
https://huggingface.co/shafin/distilbert-base-uncased-finetuned-cust-similarity-1
