### ISSUE TITLE
Documents Widget

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#842]
- build to api/links first
- add in 'document upload' native afterwards
- value for mines division as well

**Comment by carlygreenehill** [comment]
Sid wants ability to name "common" document items that a public user would see throughout the engagements/common to each type of engagement.

ie. Project Description

**Comment by tiagograf-AOT** [comment]
Documents widget have been implemented aside from "uploading" a file which is in a different ticket. closing.
