### ISSUE TITLE
Public view/Engagement preview Document widget

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#849]
As a member of the public, I want to see the most relevant documents for a specific engagement in the document widget.

Document widget shows on the widget section. Folders are clickable to reveal document links (opens on another tab)

Matches wireframes:
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/7a9aa24f-f204-4c11-a0d4-5db31cf6ea9b/specs/
https://xd.adobe.com/view/ae75b5d1-8424-4323-be5a-8bf2fe0112f3-fb26/screen/ff0716e8-5ce1-4024-b809-fff7cbba08bf/specs/

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/849?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT
