### ISSUE TITLE
Schedule Engagement banner shows wrong time

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#860]
Engagement was scheduled at 4:52 PM but the banner displays time at 00:52
![Screenshot 2022-11-15 at 4.53.06 PM.png](https://images.zenhubusercontent.com/6254616e054e9b1da214d3b1/410ec59f-4ca3-45ce-9514-1124f068768e)

**Comment by VineetBala-AOT** [comment]
This is looking good. Tested in a different time zone as well and the time showing up is PST.

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/5ca5cf1f-c95f-4e32-8fc6-766bbe153e03)

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/45ca385b-926d-43a5-aea7-9a5aabc83c20)

**Comment by carlygreenehill** [comment]
Looking good to me (I work in PST)
