### ISSUE TITLE
[BUG] discrepancies in created date/updated date

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#882]
**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by VineetBala-AOT** [comment]
All the dates are being saved as UTC in the database but shows up in PST on the screen. Screen shot for reference :

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/62b2fdbd-344b-4e41-b8c0-9d7db5d04513)

![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/08c88d9d-f4c6-40a3-9bc5-21c1be32dc4d)
