### ISSUE TITLE
Who is Listening widget - a few bugs

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#883]
Just a few things to tweak:

- If you create a new contact and click save, the contact doesn't show up on the widget. It should show up without having to add it from the drop-down.

- If you click to edit the contact and save & close, the contact is not in the widget anymore. It should still show up. (Could not reproduce in a meeting)

Consistency:

- Can we use the same icon as on the widget section and survey to remove a contact, please?
![Screen Shot 2022-11-18 at 11.11.21 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/5415b259-c1f4-4005-9e67-358a2b7a17e9)![Screen Shot 2022-11-18 at 11.11.42 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/8664f109-d295-4109-8db3-be70355ec14f)![Screen Shot 2022-11-18 at 11.11.11 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/cdc4a5ca-64fd-44e7-8782-f9d96e7f26ea)

Only the information entered should show on the "card" (internal and external) 
![Screen Shot 2022-11-18 at 10.13.00 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/d75d9583-2fbb-46e6-998a-8d9f19a6ef05)

![Screen Shot 2022-11-18 at 11.11.11 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/2e63689b-b1f1-44ca-8716-e590cfbe6327)The * should be after the label, not before.
Can you center the text in the picture box and add a bit more padding on the side, please?![Screen Shot 2022-11-18 at 11.31.43 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/34c47c1d-845c-465b-8ee0-1a7b9b6d95ad)

**Comment by tiagograf-AOT** [comment]
verified and closed
