### ISSUE TITLE
As a MET user, I want to select the reasons a comment was rejected and trigger an email to inform respondent why their comment won't be published but still taken in consideration

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#886]
If user selects **rejected** when reviewing comment(s), they see a new section:

Label: Reason for rejection
Checkboxes:
Contains personal information
Contains profanity or swear words
Other (this will be inserted in the email sent to the respondent in the following sentence: One of your comments can’t be published because of “other”) (input field)

Text: 

Clicking the “save” button will trigger an automatic email to be sent to the person who made this comment. 

Text in red: 

If there is a threat/menace in the comments, select the checkbox below. No email will be sent. Contact (contact name). 

Checkbox:
Contains threat/menace

Reason for rejection is mandatory. 
If the threat/menace checkbox is checked, no email is sent.

https://xd.adobe.com/view/7d5f6547-2523-484d-8101-a7587f9076c8-280c/screen/b8a671b2-a891-4dda-81cc-04d98bf30703/

Email template

Thank you for taking the time to fill in our survey about (project name).

We reviewed your comments and can't publish them on our public site for the following reason(s):

_- One or many of your comments contain personal information such as name, address, or other information that could identify you. 

- One or many of your comments contain swear words or profanities.

- One or many of your comments can't be published because of (other).

Your comments will still be taken in consideration and send to the proponent for consideration but won't appear on our website.

Thank you,

The EAO Team

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/886?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by saravanpa-aot** [comment]
@tiagograf-AOT or for the devs ,

Separate the rejection part and mail sending part into two separate portions. So that if other ministry comes with requirement of just rejecting without sending email , will be easy to handle it conditionally

The particular Changes will look like this

- Status update Change

- post_status_change() method which will handle email sending  ; so that we can skip or have different post_status_change() for each ministires
