### ISSUE TITLE
As a member of the public, I want to learn more about each phase of the engagement in the Engagement Phases widget (Mobile)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#888]
Same as https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/670
but vertical for mobile view.

Matches wireframes:
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/e2cc907c-749c-4dfb-bd1c-f4e547aa3588
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/8e7e58bf-1656-4336-81b9-50e1fac42fd1
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/17002b5b-acae-4f51-8637-f939d82f0854
https://xd.adobe.com/view/d0671e99-d506-4ed5-b51e-2bf6e3fcb523-8534/screen/deb9e27a-8344-4481-892c-305267404ad4

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/888?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by tiagograf-AOT** [comment]
verified & closed
