### ISSUE TITLE
remove ActionResult usage in api

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#906]
The API results are not of the standard structure since we use ActionResult . It always results in a nested format which is not ideal in many of the cases.

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/906?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by jadmsaadaot** [comment]
All CRUD operations need to be tested

**Comment by marieanik** [comment]
Do I need to UX test this @jadmsaadaot?
