### ISSUE TITLE
Swap current drag and drop library to react-beautiful-dnd

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/met-public#910]

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/910?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by saravanpa-aot** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/2437 
Check this and see which we wanna use
@jadmsaadaot @djnunez-aot
