### ISSUE TITLE
As a new user in MET, I want to see a short tutorial on how to use the tool when I first log on

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#929]
**As a** new user

**I want** to see a short tutorial on how to use MET

**so that** (reason/ why/ value) I learn to use the tool when I first log on

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by marieanik** [comment]
Closing this one as we have the user guide.
