### ISSUE TITLE
MET Site Domain

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#932]
Start activities for getting vanity url from OCIO earlier so that we dont have to rush if we have to go live earlier 

The vanity url comes as a part of branding ; for example it could look like http://engagement.gov.bc.ca/ or modernengagement.gov.bc.ca

**Comment by carlygreenehill** [comment]
[Approve-ENV-engage.eao.gov.bc.ca.pdf](https://github.com/bcgov/met-public/files/12469927/Approve-ENV-engage.eao.gov.bc.ca.pdf)

@saravanpa-aot  - we got approval. What happens next?

**Comment by VineetBala-AOT** [comment]
Verified.
