### ISSUE TITLE
Align select survey field for cloning a survey

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/met-public#946]
Fix height of text field/dropdown (they should match)

**Comment by djnunez-aot** [comment]
![image](https://user-images.githubusercontent.com/103138766/204930578-85914e10-0748-40b3-944f-f9cb69f5d997.png)

**Comment by VineetBala-AOT** [comment]
@djnunez-aot , can we please make the spacing between the header an the input same as well:
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/efee9c77-ff8d-401f-aac6-26fc1e39445e)

Also would be better if we have the drop down on the below to be of similar height as on other selections:
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/28be1c5f-6953-429f-bf50-9188c7985fcb)
