### ISSUE TITLE
Support Collapse/Expand in Doc widget Public view

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/met-public#951]
As a user I want to expand the public document widget.

I want to be able to expand the public document widget so that it is easier for the user to view the widget.

## **Acceptance Criteria**
-Collapsible Widget Tree View

### Scenario 1: 
-Given you click the expandable icon then you should see the widget expand

### Scenario 2: 
-Given you click the collapsible icon then you should see the widget expand

**Comment by tiagograf-AOT** [comment]
verified and closed
