### ISSUE TITLE
Design tweaks select widget & other icons

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#953]
Use outlines icons for the widget selection screen
https://materialui.co/material-icons-outlined/chat-bubble-outline
https://materialui.co/material-icons-outlined/people-alt
https://materialui.co/material-icons-outlined/description
0.6em
25px padding-left (icon)
10px padding-left (widget name)
#707070
Add an "s" to Document > Documents
![Screen Shot 2022-12-01 at 1.50.09 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/8e0467cd-2a44-4848-bdad-a247150933bf)

And change the icons on the document widget for :
https://materialui.co/material-icons-outlined/description (change size to 1.2rem and match "external link" icon size)
https://materialui.co/material-icons-outlined/folder (change size to 1.4rem)

**Comment by tiagograf-AOT** [comment]
verified and closed
