### ISSUE TITLE
SPIKE: Research "Crop/Edit Banner/Avatar Photo" options

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#955]
Timebox = less than a day

**Comment by jadmsaadaot** [comment]
Easy task to implement. We can follow the steps in this  article https://timetoprogram.com/crop-image-reactjs/

We can use below libraries:
- https://www.npmjs.com/package/react-image-crop
- https://www.npmjs.com/package/react-easy-crop

**Comment by jadmsaadaot** [comment]
@carlygreenehill  Easy task to implement. We can follow the steps in this article https://timetoprogram.com/crop-image-reactjs/

We can use below libraries:
- https://www.npmjs.com/package/react-image-crop
- https://www.npmjs.com/package/react-easy-crop
