### ISSUE TITLE
SPIKE: Research Video widget options

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/met-public#956]

**Comment by carlygreenehill** [comment]
Can you research...

- if we hosted the video ourselves in s3?
- if it was just a link we pulled over?
-

**Comment by jadmsaadaot** [comment]
we can stream from both s3 and multiple platforms (Youtube, facebool, vimeo, etc.) using npm react-player. We just pass the url. For s3 the videos need to be public, if not we can generate a signed url via the backend that is authenticated to stream the video

**Comment by jadmsaadaot** [comment]
![image.png](https://images.zenhubusercontent.com/61670716af0598935f770d72/9cbc5a94-0735-41c7-84d7-9d1a7452e33c)
