### ISSUE TITLE
Assign a viewer/TM a Superuser role from the User details page

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#966]
As a Superuser/Instance Admin, I want to make a viewer/TM a Superuser from the User details page.

https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/24e95953-0a12-4052-8818-9977fd6c0b79/specs/

The "Assign Superuser Role" toggle is only enabled if the user is a Superuser/Instance Admin.
The "Deactivate User" toggle is only enabled if the user is Instance Admin.
"Add to Engagement" button is disabled if user is a viewer

Superuser/Instance Admin is on the user detail page, toggles on the "Assign Superuser Role" control
https://xd.adobe.com/view/61e16dd6-919e-4374-a074-d09fd2184766-34b2/screen/dcc8725d-d39f-42f7-8627-2382608fa7cd/specs/

Superuser/Instance Admin sees the notification/confirmation message (green popup message): 
You have successfully added (user name) as a Superuser. 
"Role:" is updated to show "Superuser"
"Deactivate" and toggle off Superuser should NOT be allowed if it's for you.

**Can we have a modal that asks "Are you sure?"
and a green success confirmation notice.** 

Untoggling:
Modal also needed "Are you sure you want to?" and a green success confirmation notice.

**Comment by carlygreenehill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/966?planning-poker) with Zenhub @jadmsaadaot @tiagograf-AOT @VineetBala-AOT

**Comment by marieanik** [comment]
Covered in #1907
