### ISSUE TITLE
Engagement widget tweaks

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#979]
A few changes to the widget:

Add the "current phase" icon with text "Current Phase and Comment Period" in 13px italic next to it. All past phases will be greyed-out in #7B8283 with a 1px border in #565656.

https://xd.adobe.com/view/4f8d7697-971c-4010-9d8d-db80bf63a841-1ade/screen/52c90a20-4a75-4fa9-b95a-15dc7aa474e1/

"Learn more" link should be underlined in white (not blue), Hover in bold

Background colors for the boxes:
EE: #A8D5DD
RD: #EFBDB9
PP:#89A4C4
AD&R: #9AC0E0
EA&R: #EDC970
D: #AAA2BF
PC: #D5DE9E

Change the icon for this one:

\<svg id="Group_495" data-name="Group 495" xmlns="http://www.w3.org/2000/svg" width="72.696" height="69.501" viewBox="0 0 72.696 69.501">
  \<g id="Rectangle_167" data-name="Rectangle 167" fill="#458686" stroke="#fff" stroke-width="2">
    \<rect width="65" height="35" rx="10" stroke="none"/>
    \<rect x="1" y="1" width="63" height="33" rx="9" fill="none"/>
  \</g>
  \<g id="Group_488" data-name="Group 488" transform="translate(72.696 69.501) rotate(180)">
    \<g id="Group_487" data-name="Group 487" transform="translate(0 0)">
      \<g id="Rectangle_167-2" data-name="Rectangle 167" fill="#9be2df" stroke="#fff" stroke-width="1">
        \<rect width="65" height="35" rx="10" stroke="none"/>
        \<rect x="0.5" y="0.5" width="64" height="34" rx="9.5" fill="none"/>
      \</g>
      \<path id="Path_166" data-name="Path 166" d="M18.449,0s-7.276,32.853-7.82,20.193S0,.278,0,.278" transform="translate(37.175 33.042)" fill="#9be2df"/>
    \</g>
  \</g>
  \<path id="Path_166-2" data-name="Path 166" d="M-22838.951-17532s-8.5,36.906-9.141,22.686-12.42-22.373-12.42-22.373" transform="translate(22893.012 17560.459)" fill="#458686"/>
\</svg>

**Comment by jadmsaadaot** [comment]
Vineet observed:

on the phases widget we have a text like "
Effect Assessment & Review"
the wireframe says "
Effect Assessment & Recommendation"

**Comment by marieanik** [comment]
@jadmsaadaot

Attaching the document we have to use for correct wording. 
The page says "Recommendation" but it should be "Effects Assessment & Recommendation".
I also noticed the "recommendation" gets cut.
![Screen Shot 2022-12-16 at 5.33.57 AM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/9342889d-95ac-4b88-acb1-5dc3288da10e)
No Engagement icon for Readiness Decision.

We have to tweak the colour background for the boxes. (My bad, they are still too dark.)

Please change for the following:
EE: #cce5e9
RD: #ead0ce
PP: #bed1e7
AD&R: #bbd3e7
EA&R: #f2e1b6
D: #dbd7e5
PC: #e9eecc

For the "greyed-out" phases, let's do a #f2f2f2 background with #494949 text.
