### ISSUE TITLE
As an Admin, I can select an existing survey to clone it

### ISSUE THREAD

**Issue by sidtobias** [bcgov/met-public#98]
**As an** Admin

**I want** to select an existing survey and clone it

**so that** I can use it as a template that I can edit to customize

### Scenario 1: 
Admin clicks the "Create Survey" button on the Survey listing page OR from the engagement page.

Admin sees the "Create Survey" screen. 

Section Header: "Create Survey" (+ edit icon = widget name is editable)
Sees available options depending on the page they are coming from (https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/97 OR https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/47)
"Save & Continue" and "Cancel" buttons

Admin selects the "Clone an existing Survey" and sees:
Drop-down: Select Engagement (optional)
Drop-down:  Select Survey 
Input field to "Enter Survey Name" (pre-populated with survey name)
"Save & Continue" and "Cancel" buttons

### Scenario 2:
User clicks "Add Survey ", goes to the survey panel with all the questions from the cloned/existing survey. 

### Scenario 3:
Matches wireframes
(from Survey listing page)
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/01a280d9-bc72-4fb3-96ed-1e78bcdac199
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/719f3a59-f300-4bb3-a291-98cafc176a17
(from Engagement page)
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/bf0d9afb-1c4b-4ab3-a08f-8ed5a7b35163/
https://xd.adobe.com/view/e38dc788-12d5-4844-87ca-149d1d32d395-b6de/screen/c180802e-cc2d-4bde-9ae6-231dcce70e65/

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmsaadaot** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/98?planning-poker) with Zenhub @djnunez-aot @saravanpa-aot @tiagograf-AOT @VineetBala-AOT

**Comment by carlygreenehill** [comment]
hiya @djnunez-aot  + @saravanpa-aot  --- great work! i am able to clone a survey from the survey tab, and then later add the cloned survey to an existing engagement. 

I am also able to go into an engagement that does not have a survey, select add survey, and then clone something from there. i can also change that newly cloned survey (by adding next questions, etc.) and save it. it's all looking good!
