### ISSUE TITLE
Engagement widget - Mobile view - tweaks

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#992]
A few changes to the widget:

Move the engagement icon to the right, just above the accordion

Add the "current phase" icon (map marker) in the top right corner of the current phase (just above the engagement icon).  

![EA-Process-mobile-1.jpg](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/d7b5c996-799e-401b-8230-e277bcaaab65)

All past phases will be greyed-out in #7B8283 with a 1px border in #565656.
Same as for the horizontal version:
https://xd.adobe.com/view/4f8d7697-971c-4010-9d8d-db80bf63a841-1ade/screen/52c90a20-4a75-4fa9-b95a-15dc7aa474e1/

"Learn more" > not "read more"

Let's make the accordion the background colours only and full width (not a box within the box to maximize the space.

![Engagement-widget-mobile-open.jpg](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/6fb85c93-8051-4723-9b16-9cc78e11fafc)

Background colours for the boxes:
EE: #A8D5DD
RD: #EFBDB9
PP:#89A4C4
AD&R: #9AC0E0
EA&R: #EDC970
D: #AAA2BF
PC: #D5DE9E

For the engagement boxes, can we make them same width as the widget?

Change the icon for this one (click edit to see code):

<svg id="Group_495" data-name="Group 495" xmlns="http://www.w3.org/2000/svg" width="72.696" height="69.501" viewBox="0 0 72.696 69.501">
  <g id="Rectangle_167" data-name="Rectangle 167" fill="#458686" stroke="#fff" stroke-width="2">
    <rect width="65" height="35" rx="10" stroke="none"/>
    <rect x="1" y="1" width="63" height="33" rx="9" fill="none"/>
  </g>
  <g id="Group_488" data-name="Group 488" transform="translate(72.696 69.501) rotate(180)">
    <g id="Group_487" data-name="Group 487" transform="translate(0 0)">
      <g id="Rectangle_167-2" data-name="Rectangle 167" fill="#9be2df" stroke="#fff" stroke-width="1">
        <rect width="65" height="35" rx="10" stroke="none"/>
        <rect x="0.5" y="0.5" width="64" height="34" rx="9.5" fill="none"/>
      </g>
      <path id="Path_166" data-name="Path 166" d="M18.449,0s-7.276,32.853-7.82,20.193S0,.278,0,.278" transform="translate(37.175 33.042)" fill="#9be2df"/>
    </g>
  </g>
  <path id="Path_166-2" data-name="Path 166" d="M-22838.951-17532s-8.5,36.906-9.141,22.686-12.42-22.373-12.42-22.373" transform="translate(22893.012 17560.459)" fill="#458686"/>
</svg>

**Comment by marieanik** [comment]
@djnunez-aot Looks good for V1. We will probably do a few tweaks to that widget but I'll create another task for it. Can you please change "Recommendation" for "Effects Assessment & Recommendation" and remove the engagement icon from Readiness Decision? As soon as that's done, you can close the task.

**Comment by VineetBala-AOT** [comment]
@djnunez-aot , could you please update the text on the drop down as well:
![image.png](https://images.zenhubusercontent.com/614119663ff89097e85e7bb8/8445ef6b-afcb-4a84-99a3-2ba1d7b6513f)

cc: @marieanik
